package micro.examin.xml2woCsv;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

public class Tushar {
	public static void main(String[] args) {
		Map<Integer, Set<String>> idMsrMap = new TreeMap<>();
		for (String curr : input) {
			String[] split = curr.split(":");
			if (split.length == 2) {
				String idStr = split[0].replace("[\"\"", "").replace("\"\"]", "");
				String msrNamesStr = split[1].replace("[\"\"", "").replace("\"\"]", "");
				String[] idsArr = idStr.split("\"\",\"\"");
				String[] msrArr = msrNamesStr.split("\"\",\"\"");
				if (idsArr.length == msrArr.length) {
					for (int i = 0; i < idsArr.length; i++) {
						try {
							if (idMsrMap.containsKey(Integer.parseInt(idsArr[i]))) {
								Set<String> names = idMsrMap.get(Integer.parseInt(idsArr[i]));
								names.add(msrArr[i]);
							} else {
								Set<String> names = new HashSet<String>();
								names.add(msrArr[i]);
								idMsrMap.put(Integer.parseInt(idsArr[i]), names);
							}
						} catch (Exception e) {

						}
					}
				} else {
					System.out.println("msr/id  length ERROR FOR : " + curr);
				}
			} else {
				System.out.println("first split ERROR FOR : " + curr);
			}
		}
		for (Map.Entry<Integer, Set<String>> entry : idMsrMap.entrySet()) {
			System.out.println(entry.getKey() + " " + entry.getValue().toString());
		}
	}

	static String[] input = {"[\"\"1\"\",\"\"4\"\"]:[\"\"# New Accounts\"\",\"\"Amount Booked\"\"]",
			"[\"\"8\"\",\"\"9\"\"]:[\"\"# Apps Received\"\",\"\"# Approvals Received\"\"]",
			"[\"\"4\"\",\"\"16\"\",\"\"17\"\"]:[\"\"Total Amount Booked\"\",\"\"Approval Rate\"\",\"\"Decline Rate\"\"]",
			"[\"\"21\"\",\"\"22\"\"]:[\"\"# Total Exceptions\"\",\"\"# Exceptions to Total Approval\"\"]",
			"[\"\"26\"\",\"\"27\"\"]:[\"\"Average Age of Pending Applications\"\",\"\"Average TurnAround time\"\"]",
			"[\"\"1056\"\",\"\"1057\"\"]:[\"\"# Apps Rejected\"\",\"\"Rejected Apps %\"\"]",
			"[\"\"31\"\",\"\"32\"\",\"\"33\"\"]:[\"\"Average Bureau Enquiries\"\",\"\"Average Bureau Lines\"\",\"\"Average Bureau Score\"\"]",
			"[\"\"33\"\",\"\"36\"\",\"\"37\"\"]:[\"\"Average Bureau Score\"\",\"\"Average Approved Score\"\",\"\"Average Declined Score\"\"]",
			"[\"\"41\"\",\"\"39\"\"]:[\"\"% Of Apps Decisioned Using No Score\"\",\"\"% Of Apps Decisioned Using Score\"\"]",
			"[\"\"44\"\",\"\"45\"\"]:[\"\"High Score Override Rate\"\",\"\"Low Score Override Rate\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Recd\"\"]",
			"[\"\"951\"\",\"\"84\"\",\"\"85\"\"]:[\"\"EOP Total Outstanding\"\",\"\"EOP Delinquent Outstanding\"\",\"\"EOP Non-Delinquent Outstanding\"\"]",
			"[\"\"66\"\",\"\"611\"\",\"\"68\"\"]:[\"\"30 + (%) Coincident EOP Outstanding\"\",\"\"60 + (%) Coincident EOP Outstanding\"\",\"\"90 + (%) Coincident EOP Outstanding\"\"]",
			"[\"\"91\"\",\"\"92\"\",\"\"93\"\",\"\"94\"\",\"\"95\"\",\"\"96\"\",\"\"97\"\",\"\"98\"\"]:[\"\"0\"\",\"\"1\"\",\"\"2\"\",\"\"3\"\",\"\"4\"\",\"\"5\"\",\"\"6\"\",\"\"7\"\"]",
			"[\"\"102\"\",\"\"103\"\"]:[\"\"# Delinquent Accounts to Total Accounts\"\",\"\"# Non-Delinquent Accounts to Total Accounts\"\"]",
			"[\"\"982\"\"]:[\"\"Ever 30+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"984\"\"]:[\"\"Ever 90+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"981\"\"]:[\"\"Ever 120+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"981\"\",\"\"982\"\",\"\"983\"\",\"\"984\"\"]:[\"\"Ever 120+ DPD Outstanding to Total Amount Booked\"\",\"\"Ever 30+ DPD Outstanding to Total Amount Booked\"\",\"\"Ever 60+ DPD Outstanding to Total Amount Booked\"\",\"\"Ever 90+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"342\"\",\"\"343\"\"]:[\"\"Average APR\"\",\"\"Weighted Average APR\"\"]",
			"[\"\"344\"\",\"\"345\"\",\"\"79\"\"]:[\"\"Total Revenue\"\",\"\"Fee % ANR\"\",\"\"Revenue % ANR\"\"]",
			"[\"\"350\"\",\"\"352\"\"]:[\"\"Promotional Outstanding To Total Outstanding\"\",\"\"Non-Promotional Outstanding To Total Outstanding\"\"]",
			"[\"\"50\"\",\"\"381\"\"]:[\"\"# Accounts\"\",\"\"ANR\"\"]",
			"[\"\"382\"\",\"\"383\"\",\"\"384\"\"]:[\"\"Total Outstanding Fees\"\",\"\"Total Outstanding Interest\"\",\"\"Total Outstanding Principal\"\"]",
			"[\"\"385\"\",\"\"386\"\",\"\"387\"\"]:[\"\"Total Overdue Fees\"\",\"\"Total Overdue Interest\"\",\"\"Total Overdue Principal\"\"]",
			"[\"\"390\"\",\"\"395\"\"]:[\"\"Total Payments\"\",\"\"Net Payments To EOP Outstanding\"\"]",
			"[\"\"993\"\",\"\"994\"\"]:[\"\"Total Pre-Payment Amount\"\",\"\"Total Pre-Payment Amount to Total Outstanding\"\"]",
			"[\"\"989\"\",\"\"991\"\",\"\"990\"\"]:[\"\"Total Outstanding Of Accounts Paying Installment\"\",\"\"Total Outstanding Of Accounts Paying More Than Installment\"\",\"\"Total Outstanding Of Accounts Paying Less Than Installment\"\"]",
			"[\"\"50\"\",\"\"55\"\",\"\"951\"\"]:[\"\"# Total Accounts\"\",\"\"Avg. Loan Size\"\",\"\"EOP Outstanding\"\"]",
			"[\"\"50\"\",\"\"951\"\"]:[\"\"# Total Accounts\"\",\"\"EOP Outstanding\"\"]",
			"[\"\"414\"\",\"\"415\"\"]:[\"\"Avg Behavior Score\"\",\"\"Avg Bureau Score\"\"]",
			"[\"\"962\"\",\"\"423\"\"]:[\"\"# Bankrupt Write-Off\"\",\"\"Total Bankrupt Write-Off Amount\"\"]",
			"[\"\"958\"\",\"\"426\"\",\"\"424\"\"]:[\"\"EOP Bankrupt Outstanding\"\",\"\"EOP Bankrupt Outstanding To Total Outstanding Amount\"\",\"\"Bankrupt NCL\"\"]",
			"[\"\"81\"\",\"\"429\"\"]:[\"\"EOP Net Credit Loss Amount\"\",\"\"EOP Net Credit Loss Rate\"\"]",
			"[\"\"432\"\",\"\"948\"\"]:[\"\"Total Amount Recovered\"\",\"\"EOP Total Gross Write-off Amount\"\"]",
			"[\"\"960\"\",\"\"964\"\"]:[\"\"Total Fraud Loss\"\",\"\"Total Fraud Recovery\"\"]",
			"[\"\"444\"\"]:[\"\"Total Fraud Write-Off Amount\"\"]",
			"[\"\"66\"\",\"\"68\"\"]:[\"\"30 + (%) Coincident EOP Outstanding\"\",\"\"90 + (%) Coincident EOP Outstanding\"\"]",
			"[\"\"411\"\",\"\"412\"\"]:[\"\"# Write-Off Accounts\"\",\"\"Total Write-Off Amount\"\"]",
			"[\"\"423\"\",\"\"448\"\",\"\"444\"\"]:[\"\"Total Bankrupt Write-Off Amount\"\",\"\"Total Delinquent Write-Off Amount\"\",\"\"Total Fraud Write-Off Amount\"\"]",
			"[\"\"983\"\"]:[\"\"Ever 60+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"929\"\",\"\"932\"\"]:[\"\"# Collateral Units\"\",\"\"Original Value of Collateral Units\"\"]",
			"[\"\"933\"\",\"\"934\"\"]:[\"\"No of Accounts Foreclosed\"\",\"\"Total Amount Foreclosed\"\"]",
			"[\"\"936\"\",\"\"940\"\"]:[\"\"# Collateral Units Repossessed\"\",\"\"Value of Collateral Units Repossessed\"\"]",
			"[\"\"465\"\",\"\"466\"\"]:[\"\"# Active Accounts to Total Accounts\"\",\"\"# Inactive Accounts to Total Accounts\"\"]",
			"[\"\"472\"\",\"\"475\"\"]:[\"\"Accounts with Any Cash Spend (#)\"\",\"\"Accounts with Any Retail Spend (#)\"\"]",
			"[\"\"488\"\",\"\"489\"\"]:[\"\"VA Accounts to Total Accounts (%)\"\",\"\"InVA Accounts to Total Accounts (%)\"\"]",
			"[\"\"489\"\",\"\"491\"\"]:[\"\"InVA Accounts to Total Accounts (%)\"\",\"\"InVA Accounts to Total Attrition (%)\"\"]",
			"[\"\"488\"\",\"\"493\"\"]:[\"\"VA Accounts to Total Accounts (%)\"\",\"\"VA Accounts to Total Attrition (%)\"\"]",
			"[\"\"499\"\",\"\"500\"\"]:[\"\"Cash Spend to Total Spend (%)\"\",\"\"Retail Spend to Total Spend (%)\"\"]",
			"[\"\"503\"\",\"\"504\"\"]:[\"\"Total Cash Spend ($)\"\",\"\"Cash ENR to Cash Spend (%)\"\"]",
			"[\"\"509\"\",\"\"512\"\"]:[\"\"Total Domestic Spend ($)\"\",\"\"Total International Spend ($)\"\"]",
			"[\"\"518\"\",\"\"500\"\"]:[\"\"Total Retail Spend ($)\"\",\"\"Retail Spend to Total Spend (%)\"\"]",
			"[\"\"524\"\",\"\"527\"\"]:[\"\"Retail Frequency per Account (#)\"\",\"\"Cash Frequency per Open Account (#)\"\"]",
			"[\"\"531\"\",\"\"532\"\"]:[\"\"% Decrease In Limit\"\",\"\"% Increase In Limit\"\"]",
			"[\"\"537\"\",\"\"540\"\"]:[\"\"Revolving Accounts (#)\"\",\"\"Transacting Accounts (#)\"\"]",
			"[\"\"59\"\",\"\"61\"\"]:[\"\"Sales Utilization %\"\",\"\"Balance Utilization %\"\"]",
			"[\"\"66\"\"]:[\"\"30+ (%) Coincident EOP Outstanding\"\"]",
			"[\"\"68\"\"]:[\"\"90+ (%) Coincident EOP Outstanding\"\"]",
			"[\"\"66\"\"]:[\"\"30 + (%) Coincident Outstanding\"\"]",
			"[\"\"68\"\"]:[\"\"90 + (%) Coincident Outstanding\"\"]",
			"[\"\"552\"\",\"\"553\"\",\"\"347\"\"]:[\"\"Interchange Income - Cash\"\",\"\"Interchange Income - Retail\"\",\"\"Total Interchange Income\"\"]",
			"[\"\"555\"\",\"\"556\"\",\"\"557\"\"]:[\"\"ENR Of Purchasing, Paying Less Than Min Due\"\",\"\"ENR Of Purchasing, Paying Min Due\"\",\"\"ENR Of Purchasing, Paying More Than Min Due\"\"]",
			"[\"\"561\"\",\"\"562\"\"]:[\"\"# Non-Purchasing, Paying Accounts\"\",\"\"# Purchasing, Non-Paying Accounts\"\"]",
			"[\"\"564\"\",\"\"565\"\"]:[\"\"Total Fraud Recovery Amount\"\",\"\"Fraud Recovery Rate\"\"]",
			"[\"\"4\"\",\"\"8\"\"]:[\"\"Amount Booked\"\",\"\"# Apps Received\"\"]",
			"[\"\"8\"\",\"\"9\"\"]:[\"\"# Applications\"\",\"\"# Bookings\"\"]",
			"[\"\"344\"\"]:[\"\"Total Revenue\"\"]",
			"[\"\"75\"\"]:[\"\"Total Attrition\"\"]",
			"[\"\"66\"\"]:[\"\"30 + (%) Coincident EOP Outstanding\"\"]",
			"[\"\"418\"\",\"\"79\"\"]:[\"\"NCL __PERC__ ANR\"\",\"\"Revenue __PERC__ ANR\"\"]",
			"[\"\"503\"\",\"\"518\"\"]:[\"\"Amount Cash Sales\"\",\"\"Total Retail Sales\"\"]",
			"[\"\"81\"\",\"\"432\"\",\"\"618\"\"]:[\"\"EOP Net Credit Loss Amount\"\",\"\"Total Amount Recovered\"\",\"\"EOP Gross Credit Loss Amount\"\"]",
			"[\"\"81\"\",\"\"418\"\"]:[\"\"EOP Net Credit Loss Amount\"\",\"\"NCL __PERC__ ANR\"\"]",
			"[\"\"384\"\",\"\"383\"\",\"\"382\"\"]:[\"\"Total Outstanding Principal\"\",\"\"Total Outstanding Interest\"\",\"\"Total Outstanding Fees\"\"]",
			"[\"\"344\"\",\"\"79\"\"]:[\"\"Total Revenue\"\",\"\"Revenue __PERC__ ANR\"\"]",
			"[\"\"346\"\",\"\"345\"\"]:[\"\"Total Fee Income\"\",\"\"Fee __PERC__ ANR\"\"]",
			"[\"\"81\"\"]:[\"\"EOP Net Credit Loss Amount\"\"]",
			"[\"\"441\"\"]:[\"\"Net Fraud Loss to Total Sales\"\"]",
			"[\"\"22\"\"]:[\"\"# Exceptions to Total Approval\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"55\"\"]:[\"\"Avg Loan Size\"\"]",
			"[\"\"66\"\"]:[\"\"30 __PLUS__ __LPAREN____PERC____RPAREN__ Coincident EOP Outstanding\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"9\"\"]:[\"\"# Approvals Received\"\"]",
			"[\"\"22\"\"]:[\"\"# Exceptions to Total Approval\"\"]",
			"[\"\"344\"\"]:[\"\"Total Revenue\"\"]",
			"[\"\"81\"\",\"\"418\"\"]:[\"\"EOP Net Credit Loss Amount\"\",\"\"NCL % ANR\"\"]",
			"[\"\"379\"\"]:[\"\"EOP Outstanding\"\"]",
			"[\"\"9\"\"]:[\"\"__HASH__ Approvals Received\"\"]",
			"[\"\"9\"\"]:[\"\"# Approvals Received\"\"]",
			"[\"\"342\"\"]:[\"\"Average APR\"\"]",
			"[\"\"1038\"\",\"\"340\"\"]:[\"\"Total Fees Income\"\",\"\"Total Interest Income\"\"]",
			"[\"\"81\"\"]:[\"\"EOP Net Credit Loss Amount\"\"]",
			"[\"\"79\"\"]:[\"\"Revenue __PERC__ ANR\"\"]",
			"[\"\"432\"\",\"\"81\"\"]:[\"\"Total Amount Recovered\"\",\"\"EOP Net Credit Loss Amount\"\"]",
			"[\"\"16\"\"]:[\"\"Approval Rate\"\"]",
			"[\"\"21\"\",\"\"22\"\"]:[\"\"# Total Exceptions\"\",\"\"# Exceptions to Total Approval\"\"]",
			"[\"\"390\"\"]:[\"\"Total Payments\"\"]",
			"[\"\"952\"\"]:[\"\"Total Outstanding\"\"]",
			"[\"\"81\"\",\"\"418\"\"]:[\"\"EOP Net Credit Loss Amount\"\",\"\"NCL __PERC__ ANR\"\"]",
			"[\"\"952\"\"]:[\"\"Total Outstanding\"\"]",
			"[\"\"344\"\"]:[\"\"Total Revenue\"\"]",
			"[\"\"340\"\"]:[\"\"Total Interest Income\"\"]",
			"[\"\"951\"\"]:[\"\"EOP Total Outstanding\"\"]",
			"[\"\"952\"\"]:[\"\"Total Outstanding\"\"]",
			"[\"\"934\"\"]:[\"\"Total Amount Foreclosed\"\"]",
			"[\"\"937\"\"]:[\"\"# Collateral Units Repossessed to Total Collateral Units\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"951\"\"]:[\"\"EOP Total Outstanding\"\"]",
			"[\"\"9\"\"]:[\"\"# Approvals Received\"\"]",
			"[\"\"16\"\"]:[\"\"Approval Rate\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"9\"\"]:[\"\"# Approvals Received\"\"]",
			"[\"\"9\"\"]:[\"\"# Approvals Received\"\"]",
			"[\"\"951\"\"]:[\"\"EOP Total Outstanding\"\"]",
			"[\"\"81\"\",\"\"418\"\"]:[\"\"EOP Net Credit Loss Amount\"\",\"\"NCL __PERC__ ANR\"\"]",
			"[\"\"344\"\"]:[\"\"Total Revenue\"\"]",
			"[\"\"66\"\"]:[\"\"30 __PLUS__ __LPAREN____PERC____RPAREN__ Coincident EOP Outstanding\"\"]",
			"[\"\"951\"\"]:[\"\"EOP Total Outstanding\"\"]",
			"[\"\"9\"\"]:[\"\"__HASH__ Approvals Received\"\"]",
			"[\"\"951\"\"]:[\"\"EOP Total Outstanding\"\"]",
			"[\"\"340\"\"]:[\"\"Total Interest Income\"\"]",
			"[\"\"951\"\"]:[\"\"EOP Total Outstanding\"\"]",
			"[\"\"9\"\"]:[\"\"__HASH__ Approvals Received\"\"]",
			"[\"\"9\"\"]:[\"\"__HASH__ Approvals Received\"\"]",
			"[\"\"16\"\"]:[\"\"Approval Rate\"\"]",
			"[\"\"344\"\"]:[\"\"Total Revenue\"\"]",
			"[\"\"952\"\"]:[\"\"Total Outstanding\"\"]",
			"[\"\"9\"\"]:[\"\"# Approvals Received\"\"]",
			"[\"\"933\"\"]:[\"\"No of Accounts Foreclosed\"\"]",
			"[\"\"8\"\",\"\"9\"\"]:[\"\"# Apps Received\"\",\"\"# Approvals Received\"\"]",
			"[\"\"61\"\"]:[\"\"Balance Utilization %\"\"]",
			"[\"\"984\"\"]:[\"\"Ever 90+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"1037\"\"]:[\"\"__PERC__ Ever 90 DPD Outstanding\"\"]",
			"[\"\"1036\"\"]:[\"\"__PERC__ Ever 30 DPD Outstanding\"\"]",
			"[\"\"1036\"\"]:[\"\"% Ever 30 DPD Outstanding\"\"]",
			"[\"\"1036\"\"]:[\"\"__PERC__ Ever 30 DPD Outstanding\"\"]",
			"[\"\"1037\"\"]:[\"\"__PERC__ Ever 90 DPD Outstanding\"\"]",
			"[\"\"379\"\"]:[\"\"EOP Outstanding\"\"]",
			"[\"\"346\"\",\"\"340\"\"]:[\"\"Total Fee Income\"\",\"\"Total Interest Income\"\"]",
			"[\"\"68\"\"]:[\"\"90 __PLUS__ __LPAREN____PERC____RPAREN__ Coincident EOP Outstanding\"\"]",
			"[\"\"66\"\"]:[\"\"30 + (%) Coincident EOP Outstanding\"\"]",
			"[\"\"53\"\"]:[\"\"Outstanding/Account\"\"]",
			"[\"\"384\"\",\"\"383\"\",\"\"382\"\"]:[\"\"Total Outstanding Principal\"\",\"\"Total Outstanding Interest\"\",\"\"Total Outstanding Fees\"\"]",
			"[\"\"1\"\",\"\"50\"\",\"\"55\"\"]:[\"\"New Accounts (#)\"\",\"\"Total Accounts (#)\"\",\"\"Average Loan Size ($)\"\"]",
			"[\"\"342\"\",\"\"343\"\"]:[\"\"Average APR\"\",\"\"Weighted Average APR\"\"]",
			"[\"\"965\"\",\"\"50\"\",\"\"120\"\"]:[\"\"# 60 __PLUS__ __LPAREN____PERC____RPAREN__ Coincident Accounts\"\",\"\"# Accounts\"\",\"\"# Ever 60__PLUS__ DPD Accounts\"\"]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[\"\"635\"\",\"\"4\"\",\"\"7\"\"]:[\"\"# New Accounts\"\",\"\"Amount Booked\"\",\"\"Average Ticket size\"\"]",
			"[\"\"55\"\",\"\"379\"\",\"\"50\"\"]:[\"\"Avg Loan Size\"\",\"\"EOP Outstanding\"\",\"\"# Accounts\"\"]",
			"[\"\"31\"\",\"\"32\"\",\"\"33\"\"]:[\"\"Average Bureau Enquiries\"\",\"\"Average Bureau Lines\"\",\"\"Average Bureau Score\"\"]",
			"[\"\"50\"\",\"\"419\"\"]:[\"\"# Accounts\"\",\"\"# Bankrupt Accouts\"\"]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[\"\"66\"\"]:[\"\"30 + (%) Coincident EOP Outstanding\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"66\"\"]:[\"\"30 + (%) Coincident EOP Outstanding\"\"]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[\"\"50\"\",\"\"51\"\",\"\"53\"\",\"\"57\"\",\"\"58\"\",\"\"59\"\",\"\"61\"\",\"\"62\"\",\"\"65\"\",\"\"66\"\",\"\"68\"\",\"\"73\"\",\"\"75\"\",\"\"76\"\",\"\"79\"\",\"\"379\"\",\"\"418\"\",\"\"429\"\",\"\"465\"\",\"\"538\"\",\"\"541\"\",\"\"616\"\",\"\"395\"\",\"\"60\"\",\"\"64\"\",\"\"70\"\",\"\"72\"\"]:[\"\"# Accounts\"\",\"\"Cards In Force\"\",\"\"Outstanding/Account\"\",\"\"Retail Sales/Account\"\",\"\"Cash Sales/Account\"\",\"\"Sales Utilization %\"\",\"\"Balance Utilization %\"\",\"\"30+ (%) Coincident Accounts\"\",\"\"90+ (%) Coincident Accounts\"\",\"\"30+ (%) Coincident EOP Outstanding\"\",\"\"90+ (%) Coincident EOP Outstanding\"\",\"\"# Spending Accounts\"\",\"\"Total Attrition\"\",\"\"Sales / Account\"\",\"\"Revenue % ANR\"\",\"\"EOP Outstanding\"\",\"\"NCL % ANR\"\",\"\"EOP Net Credit Loss Rate\"\",\"\"# Active Accounts to Total Accounts\"\",\"\"# Revolving Accounts To # Total Accounts\"\",\"\"Revolve EOP ENR\"\",\"\"Credit Limit\"\",\"\"Net Payments To EOP Outstanding\"\",\"\"30+ (%) Lagged Acc\"\",\"\"30+ (%) Lagged EOP Outstanding\"\",\"\"90+ (%) Lagged Acc\"\",\"\"90+ (%) Lagged EOP Outstanding\"\"]",
			"[\"\"4\"\",\"\"635\"\"]:[\"\"Amount Booked\"\",\"\"# New Accounts\"\"]",
			"[\"\"429\"\"]:[\"\"EOP Net Credit Loss Rate\"\"]",
			"[\"\"384\"\",\"\"383\"\",\"\"382\"\"]:[\"\"Total Outstanding Principal\"\",\"\"Total Outstanding Interest\"\",\"\"Total Outstanding Fees\"\"]",
			"[\"\"81\"\",\"\"429\"\"]:[\"\"EOP Net Credit Loss Amount\"\",\"\"EOP Net Credit Loss Rate\"\"]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[]:[]",
			"[\"\"9\"\"]:[\"\"# Bookings\"\"]",
			"[\"\"951\"\",\"\"418\"\"]:[\"\"EOP Total Outstanding\"\",\"\"NCL __PERC__ ANR\"\"]",
			"[\"\"9\"\"]:[\"\"# Bookings\"\"]",
			"[\"\"9\"\",\"\"4\"\"]:[\"\"__HASH__ Bookings\"\",\"\"Total Amount Booked\"\"]",
			"[\"\"379\"\",\"\"418\"\"]:[\"\"EOP Outstanding\"\",\"\"NCL % ANR\"\"]",
			"[\"\"1038\"\",\"\"336\"\"]:[\"\"Total Fee Income\"\",\"\"Total Fee Income to Total Outstanding\"\"]",
			"[\"\"340\"\",\"\"341\"\"]:[\"\"Total Interest Income\"\",\"\"Total Interest Income to Total Outstanding\"\"]",
			"[\"\"1038\"\",\"\"340\"\",\"\"344\"\",\"\"79\"\"]:[\"\"Total Fee Income\"\",\"\"Total Interest Income\"\",\"\"Total Revenue\"\",\"\"Revenue __PERC__ ANR\"\"]",
			"[\"\"340\"\",\"\"341\"\"]:[\"\"Total Interest Income\"\",\"\"Total Interest Income to Total Outstanding\"\"]",
			"[\"\"346\"\",\"\"340\"\",\"\"79\"\"]:[\"\"Total Fee Income\"\",\"\"Total Interest Income\"\",\"\"Revenue % ANR\"\"]",
			"[\"\"346\"\",\"\"336\"\"]:[\"\"Total Fee Income\"\",\"\"Total Fee Income to Total Outstanding\"\"]",
			"[\"\"1036\"\"]:[\"\"% Ever 30 DPD Outstanding\"\"]",
			"[\"\"971\"\",\"\"991\"\"]:[\"\"__HASH__ Accounts Paying More Than Installment\"\",\"\"Total Outstanding Of Accounts Paying More Than Installment\"\"]",
			"[\"\"9\"\",\"\"11\"\",\"\"16\"\",\"\"2465\"\"]:[\"\"# Apps Approved\"\",\"\"# Decisioned Applications\"\",\"\"Approval Rate\"\",\"\"Pull through rate (%)\"\"]",
			"[\"\"8\"\",\"\"9\"\"]:[\"\"# Apps Received\"\",\"\"# Approvals Received\"\"]",
			"[\"\"4\"\",\"\"16\"\",\"\"17\"\"]:[\"\"Amount Approved\"\",\"\"Approval Rate\"\",\"\"Decline Rate\"\"]",
			"[\"\"26\"\",\"\"27\"\"]:[\"\"Average Age of Pending Applications\"\",\"\"Average TurnAround time\"\"]",
			"[\"\"1056\"\",\"\"1057\"\"]:[\"\"# Apps Rejected\"\",\"\"Rejected Apps %\"\"]",
			"[\"\"31\"\",\"\"32\"\"]:[\"\"Average Bureau Enquiries\"\",\"\"Average Bureau Lines\"\"]",
			"[\"\"36\"\"]:[\"\"Average Approved Score\"\"]",
			"[\"\"11\"\"]:[\"\"# Decissioned Applications\"\"]",
			"[\"\"44\"\",\"\"45\"\"]:[\"\"High Score Override Rate\"\",\"\"Low Score Override Rate\"\"]",
			"[\"\"8\"\",\"\"16\"\",\"\"2465\"\",\"\"30\"\",\"\"31\"\",\"\"32\"\",\"\"624\"\",\"\"49\"\"]:[\"\"# Apps Recd\"\",\"\"Approval Rate\"\",\"\"Pull through rate (%)\"\",\"\"Average Bureau Balance\"\",\"\"Average Bureau Enquiries\"\",\"\"Average Bureau Lines\"\",\"\"Hit %age\"\",\"\"Hit 2 %age\"\"]",
			"[\"\"379\"\",\"\"84\"\",\"\"85\"\"]:[\"\"EOP Total Outstanding\"\",\"\"EOP Delinquent Outstanding\"\",\"\"EOP Non-Delinquent Outstanding\"\"]",
			"[\"\"66\"\",\"\"611\"\",\"\"68\"\"]:[\"\"30 + (%) Coincident EOP Outstanding\"\",\"\"60 + % Coincident EOP Outstanding\"\",\"\"90 + (%) Coincident EOP Outstanding\"\"]",
			"[\"\"91\"\",\"\"92\"\",\"\"93\"\",\"\"94\"\",\"\"95\"\",\"\"96\"\",\"\"97\"\",\"\"98\"\"]:[\"\"0\"\",\"\"1\"\",\"\"2\"\",\"\"3\"\",\"\"4\"\",\"\"5\"\",\"\"6\"\",\"\"7\"\"]",
			"[\"\"102\"\",\"\"103\"\"]:[\"\"# Delinquent Accounts to Total Accounts\"\",\"\"# Non-Delinquent Accounts to Total Accounts\"\"]",
			"[\"\"107\"\"]:[\"\"Ever 30+ DPD ENR to Total ENR (%)\"\"]",
			"[\"\"112\"\"]:[\"\"Ever 90+ DPD ENR to Total ENR (%)\"\"]",
			"[\"\"117\"\"]:[\"\"Ever 120+ DPD ENR to Total ENR (%)\"\"]",
			"[\"\"107\"\",\"\"112\"\",\"\"117\"\",\"\"122\"\"]:[\"\"Ever 30+ DPD ENR to Total ENR (%)\"\",\"\"Ever 90+ DPD ENR to Total ENR (%)\"\",\"\"Ever 120+ DPD ENR to Total ENR (%)\"\",\"\"Ever 60+ DPD ENR to Total ENR (%)\"\"]",
			"[\"\"342\"\",\"\"343\"\"]:[\"\"Average APR\"\",\"\"Weighted Average APR\"\"]",
			"[\"\"344\"\",\"\"79\"\",\"\"345\"\"]:[\"\"Total Revenue\"\",\"\"Revenue % ANR\"\",\"\"Fee % ANR\"\"]",
			"[\"\"378\"\",\"\"381\"\"]:[\"\"# Active Accounts\"\",\"\"ANR\"\"]",
			"[\"\"388\"\"]:[\"\"EOP Total Overdue\"\"]",
			"[\"\"390\"\",\"\"395\"\"]:[\"\"Total Payments\"\",\"\"Net Payments To EOP Outstanding\"\"]",
			"[\"\"379\"\",\"\"50\"\"]:[\"\"EOP Outstanding\"\",\"\"# Accounts\"\"]",
			"[\"\"50\"\",\"\"379\"\"]:[\"\"# Total Accounts\"\",\"\"EOP Outstanding\"\"]",
			"[\"\"414\"\",\"\"415\"\"]:[\"\"Avg Behavior Score\"\",\"\"Avg Bureau Score\"\"]",
			"[\"\"423\"\",\"\"449\"\"]:[\"\"Total Bankrupt Amount\"\",\"\"# Bankrupt Write-Off\"\"]",
			"[\"\"427\"\",\"\"424\"\"]:[\"\"Bankrupt GCL\"\",\"\"Bankrupt NCL\"\"]",
			"[\"\"81\"\",\"\"429\"\"]:[\"\"EOP Net Credit Loss Amount\"\",\"\"EOP Net Credit Loss Rate\"\"]",
			"[\"\"432\"\"]:[\"\"Total Amount Recovered\"\"]",
			"[\"\"440\"\",\"\"442\"\"]:[\"\"Net Fraud Loss\"\",\"\"Net Fraud Loss to ANR\"\"]",
			"[\"\"451\"\",\"\"444\"\"]:[\"\"# Fraud Write-Off Accounts\"\",\"\"Total Fraud Write-Off Amount\"\"]",
			"[\"\"66\"\",\"\"64\"\",\"\"68\"\",\"\"72\"\"]:[\"\"30+ (%) Coincident EOP Outstanding\"\",\"\"30+ (%) Lagged EOP Outstanding\"\",\"\"90+ (%) Coincident EOP Outstanding\"\",\"\"90+ (%) Lagged EOP Outstanding\"\"]",
			"[\"\"64\"\",\"\"72\"\"]:[\"\"30 + (%) Lagged EOP Outstanding\"\",\"\"90 + (%) Lagged EOP Outstanding\"\"]",
			"[\"\"411\"\",\"\"412\"\"]:[\"\"# Write-Off Accounts\"\",\"\"Total Write-Off Amount\"\"]",
			"[\"\"2623\"\",\"\"2627\"\"]:[\"\"Total Deceased Write-Off Amount\"\",\"\"Total Pre-emptive Write-Off Amount\"\"]",
			"[\"\"122\"\"]:[\"\"Ever 60+ DPD ENR to Total ENR (%)\"\"]",
			"[\"\"139\"\",\"\"147\"\",\"\"155\"\",\"\"163\"\",\"\"171\"\",\"\"179\"\",\"\"187\"\"]:[\"\"Outstanding Roll Forward (Bucket 1)\"\",\"\"Outstanding Roll Forward (Bucket 2)\"\",\"\"Outstanding Roll Forward (Bucket 3)\"\",\"\"Outstanding Roll Forward (Bucket 4)\"\",\"\"Outstanding Roll Forward (Bucket 5)\"\",\"\"Outstanding Roll Forward (Bucket 6)\"\",\"\"Outstanding Roll Forward (Bucket 7)\"\"]",
			"[\"\"135\"\",\"\"143\"\",\"\"151\"\",\"\"159\"\",\"\"167\"\",\"\"175\"\",\"\"183\"\"]:[\"\"Accounts Roll Forward (1 TO 2)\"\",\"\"Accounts Roll Forward (2 TO 3)\"\",\"\"Accounts Roll Forward (3 TO 4)\"\",\"\"Accounts Roll Forward (4 TO 5)\"\",\"\"Accounts Roll Forward (5 TO 6)\"\",\"\"Accounts Roll Forward (6 TO 7)\"\",\"\"Accounts Roll Forward (7 TO 8)\"\"]",
			"[\"\"138\"\",\"\"146\"\",\"\"154\"\",\"\"162\"\",\"\"170\"\",\"\"178\"\"]:[\"\"Outstanding Roll Back (Bucket 2)\"\",\"\"Outstanding Roll Back (Bucket 3)\"\",\"\"Outstanding Roll Back (Bucket 4)\"\",\"\"Outstanding Roll Back (Bucket 5)\"\",\"\"Outstanding Roll Back (Bucket 6)\"\",\"\"Outstanding Roll Back (Bucket 7)\"\"]",
			"[\"\"134\"\",\"\"142\"\",\"\"150\"\",\"\"158\"\",\"\"166\"\",\"\"174\"\"]:[\"\"Accounts Roll Back (Bucket 2)\"\",\"\"Accounts Roll Back (Bucket 3)\"\",\"\"Accounts Roll Back (Bucket 4)\"\",\"\"Accounts Roll Back (Bucket 5)\"\",\"\"Accounts Roll Back (Bucket 6)\"\",\"\"Accounts Roll Back (Bucket 7)\"\"]",
			"[\"\"140\"\",\"\"148\"\",\"\"156\"\",\"\"164\"\",\"\"172\"\",\"\"180\"\",\"\"188\"\"]:[\"\"ENR Normalized (Bucket 1)\"\",\"\"ENR Normalized (Bucket 2)\"\",\"\"ENR Normalized (Bucket 3)\"\",\"\"ENR Normalized (Bucket 4)\"\",\"\"ENR Normalized (Bucket 5)\"\",\"\"ENR Normalized (Bucket 6)\"\",\"\"ENR Normalized (Bucket 7)\"\"]",
			"[\"\"136\"\",\"\"144\"\",\"\"152\"\",\"\"160\"\",\"\"168\"\",\"\"176\"\",\"\"184\"\"]:[\"\"Accounts Stabilized (Bucket 1)\"\",\"\"Accounts Stabilized (Bucket 2)\"\",\"\"Accounts Stabilized (Bucket 3)\"\",\"\"Accounts Stabilized (Bucket 4)\"\",\"\"Accounts Stabilized (Bucket 5)\"\",\"\"Accounts Stabilized (Bucket 6)\"\",\"\"Accounts Stabilized (Bucket 7)\"\"]",
			"[\"\"137\"\",\"\"145\"\",\"\"153\"\",\"\"161\"\",\"\"169\"\",\"\"177\"\"]:[\"\"ENR Normalized (Bucket 2)\"\",\"\"ENR Normalized (Bucket 3)\"\",\"\"ENR Normalized (Bucket 4)\"\",\"\"ENR Normalized (Bucket 5)\"\",\"\"ENR Normalized (Bucket 6)\"\",\"\"ENR Normalized (Bucket 7)\"\"]",
			"[\"\"231\"\",\"\"233\"\",\"\"235\"\",\"\"237\"\",\"\"241\"\",\"\"617\"\",\"\"243\"\"]:[\"\"EOP Accounts Net Flow Rate (1 TO 2)\"\",\"\"EOP Accounts Net Flow Rate (2 TO 3)\"\",\"\"EOP Accounts Net Flow Rate (3 TO 4)\"\",\"\"EOP Accounts Net Flow Rate (4 TO 5)\"\",\"\"EOP Accounts Net Flow Rate (6 TO 7)\"\",\"\"EOP Accounts Net Flow Rate (5 TO 6)\"\",\"\"EOP Accounts Net Flow Rate (7 TO 8)\"\"]",
			"[\"\"232\"\",\"\"234\"\",\"\"236\"\",\"\"238\"\",\"\"239\"\",\"\"242\"\",\"\"244\"\"]:[\"\"EOP Outstanding Net Flow Rate (1 TO 2)\"\",\"\"EOP Outstanding Net Flow Rate (2 TO 3)\"\",\"\"EOP Outstanding Net Flow Rate (3 TO 4)\"\",\"\"EOP Outstanding Net Flow Rate (4 TO 5)\"\",\"\"EOP Outstanding Net Flow Rate (5 TO 6)\"\",\"\"EOP Outstanding Net Flow Rate (6 TO 7)\"\",\"\"EOP Outstanding Net Flow Rate (7 TO 8)\"\"]",
			"[\"\"139\"\",\"\"147\"\",\"\"155\"\",\"\"163\"\",\"\"171\"\",\"\"179\"\",\"\"187\"\"]:[\"\"Outstanding Worsen (1)\"\",\"\"Outstanding Worsen (2)\"\",\"\"Outstanding Worsen (3)\"\",\"\"Outstanding Worsen (4)\"\",\"\"Outstanding Worsen (5)\"\",\"\"Outstanding Worsen (6)\"\",\"\"Outstanding Worsen WO\"\"]",
			"[\"\"135\"\",\"\"143\"\",\"\"151\"\",\"\"159\"\",\"\"167\"\",\"\"175\"\",\"\"183\"\"]:[\"\"Accounts Worsen (1)\"\",\"\"Accounts Worsen (2)\"\",\"\"Accounts Worsen (3)\"\",\"\"Accounts Worsen (4)\"\",\"\"Accounts Worsen (5)\"\",\"\"Accounts Worsen (6)\"\",\"\"Accounts Worsen (7)\"\"]",
			"[\"\"138\"\",\"\"146\"\",\"\"154\"\",\"\"162\"\",\"\"170\"\",\"\"178\"\"]:[\"\"EOP Outstanding Roll Back (2 TO 1)\"\",\"\"EOP Outstanding Roll Back (3 TO 2)\"\",\"\"EOP Outstanding Roll Back (4 TO 3)\"\",\"\"EOP Outstanding Roll Back (5 TO 4)\"\",\"\"EOP Outstanding Roll Back (6 TO 5)\"\",\"\"EOP Outstanding Roll Back (7 TO 6)\"\"]",
			"[\"\"134\"\",\"\"142\"\",\"\"150\"\",\"\"158\"\",\"\"166\"\",\"\"174\"\"]:[\"\"Accounts Roll Back (2 TO 1)\"\",\"\"Accounts Roll Back (3 TO 2)\"\",\"\"Accounts Roll Back (4 TO 3)\"\",\"\"Accounts Roll Back (5 TO 4)\"\",\"\"Accounts Roll Back (6 TO 5)\"\",\"\"Accounts Roll Back (7 TO 6)\"\"]",
			"[\"\"140\"\",\"\"148\"\",\"\"156\"\",\"\"164\"\",\"\"172\"\",\"\"180\"\",\"\"188\"\"]:[\"\"Outstanding Hold (1)\"\",\"\"Outstanding Hold (2)\"\",\"\"Outstanding Hold (3)\"\",\"\"Outstanding Hold (4)\"\",\"\"Outstanding Hold (5)\"\",\"\"Outstanding Hold (6)\"\",\"\"Outstanding Hold (7)\"\"]",
			"[\"\"136\"\",\"\"144\"\",\"\"152\"\",\"\"160\"\",\"\"168\"\",\"\"176\"\",\"\"184\"\"]:[\"\"Accounts Hold (1)\"\",\"\"Accounts Hold (2)\"\",\"\"Accounts Hold (3)\"\",\"\"Accounts Hold (4)\"\",\"\"Accounts Hold (5)\"\",\"\"Accounts Hold (6)\"\",\"\"Accounts Hold (7)\"\"]",
			"[\"\"8\"\",\"\"9\"\"]:[\"\"# Apps Received\"\",\"\"# Approvals Received\"\"]",
			"[\"\"4\"\",\"\"16\"\"]:[\"\"Amount Booked\"\",\"\"Approval Rate\"\"]",
			"[\"\"21\"\",\"\"22\"\"]:[\"\"# Total Exceptions\"\",\"\"# Exceptions to Total Approval\"\"]",
			"[\"\"26\"\",\"\"27\"\"]:[\"\"Average Age of Pending Applications\"\",\"\"Average TurnAround time\"\"]",
			"[\"\"31\"\",\"\"32\"\",\"\"33\"\"]:[\"\"Average Bureau Enquiries\"\",\"\"Average Bureau Lines\"\",\"\"Average Bureau Score\"\"]",
			"[\"\"33\"\",\"\"36\"\",\"\"37\"\"]:[\"\"Average Bureau Score\"\",\"\"Average Approved Score\"\",\"\"Average Declined Score\"\"]",
			"[\"\"11\"\",\"\"39\"\"]:[\"\"# Decissioned Applications\"\",\"\"% Of Apps Decisioned Using Score\"\"]",
			"[\"\"44\"\",\"\"45\"\"]:[\"\"High Score Override Rate\"\",\"\"Low Score Override Rate\"\"]",
			"[\"\"8\"\",\"\"16\"\",\"\"30\"\",\"\"31\"\",\"\"32\"\",\"\"624\"\"]:[\"\"# Apps Recd\"\",\"\"Approval Rate\"\",\"\"Average Bureau Balance\"\",\"\"Average Bureau Enquiries\"\",\"\"Average Bureau Lines\"\",\"\"Hit %age\"\"]",
			"[\"\"379\"\",\"\"84\"\",\"\"85\"\"]:[\"\"EOP Total Outstanding\"\",\"\"EOP Delinquent Outstanding\"\",\"\"EOP Non-Delinquent Outstanding\"\"]",
			"[\"\"66\"\",\"\"611\"\",\"\"68\"\"]:[\"\"30 + (%) Coincident EOP Outstanding\"\",\"\"60 + (%) Coincident EOP Outstanding\"\",\"\"90 + (%) Coincident EOP Outstanding\"\"]",
			"[\"\"102\"\",\"\"103\"\"]:[\"\"# Delinquent Accounts to Total Accounts\"\",\"\"# Non-Delinquent Accounts to Total Accounts\"\"]",
			"[\"\"982\"\"]:[\"\"Ever 30+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"984\"\"]:[\"\"Ever 90+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"981\"\"]:[\"\"Ever 120+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"982\"\",\"\"983\"\",\"\"984\"\",\"\"981\"\"]:[\"\"Ever 30+ DPD Outstanding to Total Amount Booked\"\",\"\"Ever 60+ DPD Outstanding to Total Amount Booked\"\",\"\"Ever 90+ DPD Outstanding to Total Amount Booked\"\",\"\"Ever 120+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"342\"\",\"\"343\"\"]:[\"\"Average APR\"\",\"\"Weighted Average APR\"\"]",
			"[\"\"344\"\",\"\"79\"\",\"\"345\"\"]:[\"\"Total Revenue\"\",\"\"Revenue % ANR\"\",\"\"Fee % ANR\"\"]",
			"[\"\"350\"\",\"\"352\"\"]:[\"\"Promotional Outstanding To Total Outstanding\"\",\"\"Non-Promotional Outstanding To Total Outstanding\"\"]",
			"[\"\"50\"\",\"\"379\"\",\"\"381\"\"]:[\"\"# Accounts\"\",\"\"EOP Outstanding\"\",\"\"ANR\"\"]",
			"[\"\"382\"\",\"\"383\"\",\"\"384\"\"]:[\"\"Total Outstanding Fees\"\",\"\"Total Outstanding Interest\"\",\"\"Total Outstanding Principal\"\"]",
			"[\"\"385\"\",\"\"386\"\",\"\"387\"\"]:[\"\"Total Overdue Fees\"\",\"\"Total Overdue Interest\"\",\"\"Total Overdue Principal\"\"]",
			"[\"\"390\"\",\"\"395\"\"]:[\"\"Total Payments\"\",\"\"Net Payments To EOP Outstanding\"\"]",
			"[\"\"50\"\",\"\"379\"\"]:[\"\"# Accounts\"\",\"\"EOP Outstanding\"\"]",
			"[\"\"379\"\",\"\"1405\"\"]:[\"\"EOP Outstanding\"\",\"\"ENR %\"\"]",
			"[\"\"50\"\",\"\"379\"\"]:[\"\"# Total Accounts\"\",\"\"EOP Outstanding\"\"]",
			"[\"\"414\"\",\"\"415\"\"]:[\"\"Avg Behavior Score\"\",\"\"Avg Bureau Score\"\"]",
			"[\"\"449\"\",\"\"423\"\"]:[\"\"# Bankrupt Write-Off\"\",\"\"Total Bankrupt Write-Off Amount\"\"]",
			"[\"\"425\"\",\"\"426\"\",\"\"424\"\"]:[\"\"EOP Bankrupt Outstanding\"\",\"\"EOP Bankrupt Outstanding To Total Outstanding Amount\"\",\"\"Bankrupt NCL\"\"]",
			"[\"\"81\"\",\"\"429\"\"]:[\"\"EOP Net Credit Loss Amount\"\",\"\"EOP Net Credit Loss Rate\"\"]",
			"[\"\"432\"\"]:[\"\"Total Amount Recovered\"\"]",
			"[\"\"964\"\",\"\"960\"\"]:[\"\"Total Fraud Recovery\"\",\"\"Total Fraud Loss\"\"]",
			"[\"\"451\"\",\"\"444\"\"]:[\"\"# Fraud Write-Off Accounts\"\",\"\"Total Fraud Write-Off Amount\"\"]",
			"[\"\"66\"\",\"\"64\"\",\"\"68\"\",\"\"72\"\"]:[\"\"30 + (%) Coincident EOP Outstanding\"\",\"\"30 + (%) Lagged EOP Outstanding\"\",\"\"90 + (%) Coincident EOP Outstanding\"\",\"\"90 + (%) Lagged EOP Outstanding\"\"]",
			"[\"\"64\"\",\"\"72\"\"]:[\"\"30 + (%) Lagged EOP Outstanding\"\",\"\"90 + (%) Lagged EOP Outstanding\"\"]",
			"[\"\"423\"\",\"\"448\"\",\"\"444\"\"]:[\"\"Total Bankrupt Write-Off Amount\"\",\"\"Total Delinquent Write-Off Amount\"\",\"\"Total Fraud Write-Off Amount\"\"]",
			"[\"\"983\"\"]:[\"\"Ever 60+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"66\"\"]:[\"\"30 + (%) Coincident Outstanding\"\"]",
			"[\"\"68\"\"]:[\"\"90 + (%) Coincident Outstanding\"\"]",
			"[\"\"1038\"\",\"\"336\"\"]:[\"\"Total Fee Income\"\",\"\"Total Fee Income to Total Outstanding\"\"]",
			"[\"\"340\"\",\"\"341\"\"]:[\"\"Total Interest Income\"\",\"\"Total Interest Income to Total Outstanding\"\"]",
			"[\"\"1038\"\",\"\"340\"\",\"\"344\"\",\"\"79\"\"]:[\"\"Total Fee Income\"\",\"\"Total Interest Income\"\",\"\"Total Revenue\"\",\"\"Revenue __PERC__ ANR\"\"]",
			"[\"\"131\"\",\"\"139\"\",\"\"147\"\",\"\"155\"\",\"\"163\"\",\"\"171\"\",\"\"179\"\",\"\"187\"\",\"\"195\"\",\"\"203\"\",\"\"211\"\",\"\"219\"\",\"\"227\"\"]:[\"\"EOP Outstanding Roll Forward (Bucket 0)\"\",\"\"EOP Outstanding Roll Forward (Bucket 1)\"\",\"\"EOP Outstanding Roll Forward (Bucket 2)\"\",\"\"EOP Outstanding Roll Forward (Bucket 3)\"\",\"\"EOP Outstanding Roll Forward (Bucket 4)\"\",\"\"EOP Outstanding Roll Forward (Bucket 5)\"\",\"\"EOP Outstanding Roll Forward (Bucket 6)\"\",\"\"EOP Outstanding Roll Forward (Bucket 7)\"\",\"\"EOP Outstanding Roll Forward (Bucket 8)\"\",\"\"EOP Outstanding Roll Forward (Bucket 9)\"\",\"\"EOP Outstanding Roll Forward (Bucket 10)\"\",\"\"EOP Outstanding Roll Forward (Bucket 11)\"\",\"\"EOP Outstanding Roll Forward (Bucket 12)\"\"]",
			"[\"\"127\"\",\"\"135\"\",\"\"143\"\",\"\"151\"\",\"\"159\"\",\"\"167\"\",\"\"175\"\",\"\"183\"\",\"\"191\"\",\"\"199\"\",\"\"207\"\",\"\"215\"\",\"\"223\"\"]:[\"\"Accounts Roll Forward (Bucket 0)\"\",\"\"Accounts Roll Forward (Bucket 1)\"\",\"\"Accounts Roll Forward (Bucket 2)\"\",\"\"Accounts Roll Forward (Bucket 3)\"\",\"\"Accounts Roll Forward (Bucket 4)\"\",\"\"Accounts Roll Forward (Bucket 5)\"\",\"\"Accounts Roll Forward (Bucket 6)\"\",\"\"Accounts Roll Forward (Bucket 7)\"\",\"\"Accounts Roll Forward (Bucket 8)\"\",\"\"Accounts Roll Forward (Bucket 9)\"\",\"\"Accounts Roll Forward (Bucket 10)\"\",\"\"Accounts Roll Forward (Bucket 11)\"\",\"\"Accounts Roll Forward (Bucket 12)\"\"]",
			"[\"\"130\"\",\"\"138\"\",\"\"146\"\",\"\"154\"\",\"\"162\"\",\"\"170\"\",\"\"178\"\",\"\"186\"\",\"\"194\"\",\"\"202\"\",\"\"210\"\",\"\"218\"\",\"\"226\"\"]:[\"\"EOP Outstanding Roll Back (Bucket 1)\"\",\"\"EOP Outstanding Roll Back (Bucket 2)\"\",\"\"EOP Outstanding Roll Back (Bucket 3)\"\",\"\"EOP Outstanding Roll Back (Bucket 4)\"\",\"\"EOP Outstanding Roll Back (Bucket 5)\"\",\"\"EOP Outstanding Roll Back (Bucket 6)\"\",\"\"EOP Outstanding Roll Back (Bucket 7)\"\",\"\"EOP Outstanding Roll Back (Bucket 8)\"\",\"\"EOP Outstanding Roll Back (Bucket 9)\"\",\"\"EOP Outstanding Roll Back (Bucket 10)\"\",\"\"EOP Outstanding Roll Back (Bucket 11)\"\",\"\"EOP Outstanding Roll Back (Bucket 12)\"\",\"\"EOP Outstanding Roll Back (Bucket 13)\"\"]",
			"[\"\"126\"\",\"\"134\"\",\"\"142\"\",\"\"150\"\",\"\"158\"\",\"\"166\"\",\"\"174\"\",\"\"182\"\",\"\"190\"\",\"\"198\"\",\"\"206\"\",\"\"214\"\",\"\"222\"\"]:[\"\"Accounts Roll Back (Bucket 1)\"\",\"\"Accounts Roll Back (Bucket 2)\"\",\"\"Accounts Roll Back (Bucket 3)\"\",\"\"Accounts Roll Back (Bucket 4)\"\",\"\"Accounts Roll Back (Bucket 5)\"\",\"\"Accounts Roll Back (Bucket 6)\"\",\"\"Accounts Roll Back (Bucket 7)\"\",\"\"Accounts Roll Back (Bucket 8)\"\",\"\"Accounts Roll Back (Bucket 9)\"\",\"\"Accounts Roll Back (Bucket 10)\"\",\"\"Accounts Roll Back (Bucket 11)\"\",\"\"Accounts Roll Back (Bucket 12)\"\",\"\"Accounts Roll Back (Bucket 13)\"\"]",
			"[\"\"132\"\",\"\"140\"\",\"\"148\"\",\"\"156\"\",\"\"164\"\",\"\"172\"\",\"\"180\"\",\"\"188\"\",\"\"196\"\",\"\"204\"\",\"\"212\"\",\"\"220\"\",\"\"228\"\"]:[\"\"EOP Outstanding Stabilized Rate (Bucket 0)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 1)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 2)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 3)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 4)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 5)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 6)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 7)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 8)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 9)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 10)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 11)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 12)\"\"]",
			"[\"\"128\"\",\"\"136\"\",\"\"144\"\",\"\"152\"\",\"\"160\"\",\"\"168\"\",\"\"176\"\",\"\"184\"\",\"\"192\"\",\"\"200\"\",\"\"208\"\",\"\"216\"\",\"\"224\"\"]:[\"\"Accounts Stabilized Rate (Bucket 0)\"\",\"\"Accounts Stabilized Rate (Bucket 1)\"\",\"\"Accounts Stabilized Rate (Bucket 2)\"\",\"\"Accounts Stabilized Rate (Bucket 3)\"\",\"\"Accounts Stabilized Rate (Bucket 4)\"\",\"\"Accounts Stabilized Rate (Bucket 5)\"\",\"\"Accounts Stabilized Rate (Bucket 6)\"\",\"\"Accounts Stabilized Rate (Bucket 7)\"\",\"\"Accounts Stabilized Rate (Bucket 8)\"\",\"\"Accounts Stabilized Rate (Bucket 9)\"\",\"\"Accounts Stabilized Rate (Bucket 10)\"\",\"\"Accounts Stabilized Rate (Bucket 11)\"\",\"\"Accounts Stabilized Rate (Bucket 12)\"\"]",
			"[\"\"129\"\",\"\"137\"\",\"\"145\"\",\"\"153\"\",\"\"161\"\",\"\"169\"\",\"\"177\"\",\"\"185\"\",\"\"193\"\",\"\"201\"\",\"\"209\"\",\"\"217\"\",\"\"225\"\"]:[\"\"EOP Outstanding Normalized (Bucket 1)\"\",\"\"EOP Outstanding Normalized (Bucket 2)\"\",\"\"EOP Outstanding Normalized (Bucket 3)\"\",\"\"EOP Outstanding Normalized (Bucket 4)\"\",\"\"EOP Outstanding Normalized (Bucket 5)\"\",\"\"EOP Outstanding Normalized (Bucket 6)\"\",\"\"EOP Outstanding Normalized (Bucket 7)\"\",\"\"EOP Outstanding Normalized (Bucket 8)\"\",\"\"EOP Outstanding Normalized (Bucket 9)\"\",\"\"EOP Outstanding Normalized (Bucket 10)\"\",\"\"EOP Outstanding Normalized (Bucket 11)\"\",\"\"EOP Outstanding Normalized (Bucket 12)\"\",\"\"EOP Outstanding Normalized (Bucket 13)\"\"]",
			"[\"\"125\"\",\"\"133\"\",\"\"141\"\",\"\"149\"\",\"\"157\"\",\"\"165\"\",\"\"173\"\",\"\"181\"\",\"\"189\"\",\"\"197\"\",\"\"205\"\",\"\"213\"\",\"\"221\"\"]:[\"\"Accounts Normalized (Bucket 1)\"\",\"\"Accounts Normalized (Bucket 2)\"\",\"\"Accounts Normalized (Bucket 3)\"\",\"\"Accounts Normalized (Bucket 4)\"\",\"\"Accounts Normalized (Bucket 5)\"\",\"\"Accounts Normalized (Bucket 6)\"\",\"\"Accounts Normalized (Bucket 7)\"\",\"\"Accounts Normalized (Bucket 8)\"\",\"\"Accounts Normalized (Bucket 9)\"\",\"\"Accounts Normalized (Bucket 10)\"\",\"\"Accounts Normalized (Bucket 11)\"\",\"\"Accounts Normalized (Bucket 12)\"\",\"\"Accounts Normalized (Bucket 13)\"\"]",
			"[\"\"229\"\",\"\"231\"\",\"\"233\"\",\"\"235\"\",\"\"237\"\",\"\"617\"\",\"\"241\"\",\"\"243\"\"]:[\"\"EOP Accounts Net Flow Rate (0 TO 1)\"\",\"\"EOP Accounts Net Flow Rate (1 TO 2)\"\",\"\"EOP Accounts Net Flow Rate (2 TO 3)\"\",\"\"EOP Accounts Net Flow Rate (3 TO 4)\"\",\"\"EOP Accounts Net Flow Rate (4 TO 5)\"\",\"\"EOP Accounts Net Flow Rate (5 TO 6)\"\",\"\"EOP Accounts Net Flow Rate (6 TO 7)\"\",\"\"EOP Accounts Net Flow Rate (7 TO 8)\"\"]",
			"[\"\"230\"\",\"\"232\"\",\"\"234\"\",\"\"236\"\",\"\"238\"\",\"\"239\"\",\"\"242\"\",\"\"244\"\"]:[\"\"EOP Outstanding Net Flow Rate (0 TO 1)\"\",\"\"EOP Outstanding Net Flow Rate (1 TO 2)\"\",\"\"EOP Outstanding Net Flow Rate (2 TO 3)\"\",\"\"EOP Outstanding Net Flow Rate (3 TO 4)\"\",\"\"EOP Outstanding Net Flow Rate (4 TO 5)\"\",\"\"EOP Outstanding Net Flow Rate (5 TO 6)\"\",\"\"EOP Outstanding Net Flow Rate (6 TO 7)\"\",\"\"EOP Outstanding Net Flow Rate (7 TO 8)\"\"]",
			"[\"\"131\"\",\"\"139\"\",\"\"147\"\",\"\"155\"\",\"\"163\"\",\"\"171\"\",\"\"179\"\",\"\"187\"\",\"\"195\"\",\"\"203\"\",\"\"211\"\",\"\"219\"\",\"\"227\"\"]:[\"\"Outstanding Worsen (0)\"\",\"\"Outstanding Worsen (1)\"\",\"\"Outstanding Worsen (2)\"\",\"\"Outstanding Worsen (3)\"\",\"\"Outstanding Worsen (4)\"\",\"\"Outstanding Worsen (5)\"\",\"\"Outstanding Worsen (6)\"\",\"\"Outstanding Worsen (7)\"\",\"\"Outstanding Worsen (8)\"\",\"\"Outstanding Worsen (9)\"\",\"\"Outstanding Worsen (10)\"\",\"\"Outstanding Worsen (11)\"\",\"\"Outstanding Worsen (12)\"\"]",
			"[\"\"127\"\",\"\"135\"\",\"\"143\"\",\"\"151\"\",\"\"159\"\",\"\"167\"\",\"\"175\"\",\"\"183\"\",\"\"191\"\",\"\"199\"\",\"\"207\"\",\"\"215\"\",\"\"223\"\"]:[\"\"Accounts Worsen (0)\"\",\"\"Accounts Worsen (1)\"\",\"\"Accounts Worsen (2)\"\",\"\"Accounts Worsen (3)\"\",\"\"Accounts Worsen (4)\"\",\"\"Accounts Worsen (5)\"\",\"\"Accounts Worsen (6)\"\",\"\"Accounts Worsen (7)\"\",\"\"Accounts Worsen (8)\"\",\"\"Accounts Worsen (9)\"\",\"\"Accounts Worsen (10)\"\",\"\"Accounts Worsen (11)\"\",\"\"Accounts Worsen (12)\"\"]",
			"[\"\"130\"\",\"\"138\"\",\"\"146\"\",\"\"154\"\",\"\"162\"\",\"\"170\"\",\"\"178\"\",\"\"186\"\",\"\"194\"\",\"\"202\"\",\"\"210\"\",\"\"218\"\",\"\"226\"\"]:[\"\"Outstanding Improve (1)\"\",\"\"Outstanding Improve (2)\"\",\"\"Outstanding Improve (3)\"\",\"\"Outstanding Improve (4)\"\",\"\"Outstanding Improve (5)\"\",\"\"Outstanding Improve (6)\"\",\"\"Outstanding Improve (7)\"\",\"\"Outstanding Improve (8)\"\",\"\"Outstanding Improve (9)\"\",\"\"Outstanding Improve (10)\"\",\"\"Outstanding Improve (11)\"\",\"\"Outstanding Improve (12)\"\",\"\"Outstanding Improve (13)\"\"]",
			"[\"\"126\"\",\"\"134\"\",\"\"142\"\",\"\"150\"\",\"\"158\"\",\"\"166\"\",\"\"174\"\",\"\"182\"\",\"\"190\"\",\"\"198\"\",\"\"206\"\",\"\"214\"\",\"\"222\"\"]:[\"\"Accounts Improve (1)\"\",\"\"Accounts Improve (2)\"\",\"\"Accounts Improve (3)\"\",\"\"Accounts Improve (4)\"\",\"\"Accounts Improve (5)\"\",\"\"Accounts Improve (6)\"\",\"\"Accounts Improve (7)\"\",\"\"Accounts Improve (8)\"\",\"\"Accounts Improve (9)\"\",\"\"Accounts Improve (10)\"\",\"\"Accounts Improve (11)\"\",\"\"Accounts Improve (12)\"\",\"\"Accounts Improve (13)\"\"]",
			"[\"\"132\"\",\"\"140\"\",\"\"148\"\",\"\"156\"\",\"\"164\"\",\"\"172\"\",\"\"180\"\",\"\"188\"\",\"\"196\"\",\"\"204\"\",\"\"212\"\",\"\"220\"\",\"\"228\"\"]:[\"\"Outstanding Hold (0)\"\",\"\"Outstanding Hold (1)\"\",\"\"Outstanding Hold (2)\"\",\"\"Outstanding Hold (3)\"\",\"\"Outstanding Hold (4)\"\",\"\"Outstanding Hold (5)\"\",\"\"Outstanding Hold (6)\"\",\"\"Outstanding Hold (7)\"\",\"\"Outstanding Hold (8)\"\",\"\"Outstanding Hold (9)\"\",\"\"Outstanding Hold (10)\"\",\"\"Outstanding Hold (11)\"\",\"\"Outstanding Hold (12)\"\"]",
			"[\"\"128\"\",\"\"136\"\",\"\"144\"\",\"\"152\"\",\"\"160\"\",\"\"168\"\",\"\"176\"\",\"\"184\"\",\"\"192\"\",\"\"200\"\",\"\"208\"\",\"\"216\"\",\"\"224\"\"]:[\"\"Accounts Hold (0)\"\",\"\"Accounts Hold (1)\"\",\"\"Accounts Hold (2)\"\",\"\"Accounts Hold (3)\"\",\"\"Accounts Hold (4)\"\",\"\"Accounts Hold (5)\"\",\"\"Accounts Hold (6)\"\",\"\"Accounts Hold (7)\"\",\"\"Accounts Hold (8)\"\",\"\"Accounts Hold (9)\"\",\"\"Accounts Hold (10)\"\",\"\"Accounts Hold (11)\"\",\"\"Accounts Hold (12)\"\"]",
			"[\"\"21\"\",\"\"22\"\"]:[\"\"# Total Deviations\"\",\"\"Number of Deviations to total approval %\"\"]",
			"[\"\"26\"\",\"\"27\"\"]:[\"\"Average Age of Pending Applications\"\",\"\"Average TurnAround time\"\"]",
			"[\"\"1056\"\",\"\"1057\"\"]:[\"\"# Apps Rejected\"\",\"\"Rejected Apps %\"\"]",
			"[\"\"31\"\",\"\"32\"\",\"\"33\"\"]:[\"\"Average Bureau Enquiries\"\",\"\"Average Bureau Lines\"\",\"\"Average Bureau Score\"\"]",
			"[\"\"33\"\",\"\"36\"\",\"\"37\"\"]:[\"\"Average Bureau Score\"\",\"\"Average Approved Score\"\",\"\"Average Declined Score\"\"]",
			"[\"\"41\"\",\"\"39\"\"]:[\"\"% Of Apps Decisioned Using No Score\"\",\"\"% Of Apps Decisioned Using Score\"\"]",
			"[\"\"42\"\",\"\"43\"\"]:[\"\"# High Score Overrides\"\",\"\"# Low Score Overrides\"\"]",
			"[\"\"952\"\",\"\"84\"\",\"\"85\"\"]:[\"\"Total Outstanding\"\",\"\"EOP Delinquent Outstanding\"\",\"\"EOP Non-Delinquent Outstanding\"\"]",
			"[\"\"66\"\",\"\"611\"\",\"\"68\"\"]:[\"\"30+ (%) Coincident EOP Outstanding\"\",\"\"60+ (%) Coincident EOP Outstanding\"\",\"\"90+ (%) Coincident EOP Outstanding\"\"]",
			"[\"\"91\"\",\"\"92\"\",\"\"93\"\",\"\"94\"\",\"\"95\"\",\"\"96\"\",\"\"97\"\",\"\"98\"\"]:[\"\"Bucket 0\"\",\"\"Bucket 1\"\",\"\"Bucket 2\"\",\"\"Bucket 3\"\",\"\"Bucket 4\"\",\"\"Bucket 5\"\",\"\"Bucket 6\"\",\"\"Bucket 7\"\"]",
			"[\"\"102\"\",\"\"103\"\"]:[\"\"# Delinquent Accounts to Total Accounts\"\",\"\"# Non-Delinquent Accounts to Total Accounts\"\"]",
			"[\"\"342\"\",\"\"343\"\"]:[\"\"Average APR\"\",\"\"Weighted Average APR\"\"]",
			"[\"\"344\"\"]:[\"\"Total Revenue\"\"]",
			"[\"\"351\"\",\"\"352\"\"]:[\"\"Non-Promotional Outstanding\"\",\"\"Non-Promotional Outstanding To Total Outstanding\"\"]",
			"[\"\"50\"\",\"\"381\"\"]:[\"\"# Accounts\"\",\"\"ANR\"\"]",
			"[\"\"383\"\",\"\"384\"\",\"\"952\"\"]:[\"\"Total Outstanding Interest\"\",\"\"Total Outstanding Principal\"\",\"\"Total Outstanding\"\"]",
			"[\"\"386\"\",\"\"387\"\"]:[\"\"Total Overdue Interest\"\",\"\"Total Overdue Principal\"\"]",
			"[\"\"395\"\",\"\"992\"\"]:[\"\"Net Payments To EOP Outstanding\"\",\"\"Total Payment Amount\"\"]",
			"[\"\"50\"\",\"\"952\"\"]:[\"\"# Accounts\"\",\"\"Total Outstanding\"\"]",
			"[\"\"952\"\"]:[\"\"Total Outstanding\"\"]",
			"[\"\"414\"\",\"\"415\"\"]:[\"\"Avg Behavior Score\"\",\"\"Avg Bureau Score\"\"]",
			"[\"\"1045\"\",\"\"426\"\"]:[\"\"Bankrupt OS\"\",\"\"Bankrupt OS To Total OS (%)\"\"]",
			"[\"\"411\"\",\"\"412\"\"]:[\"\"# Write Off Account\"\",\"\"Total Write Off Amount\"\"]",
			"[\"\"432\"\"]:[\"\"Total Amount Recovered\"\"]",
			"[\"\"964\"\",\"\"960\"\"]:[\"\"Total Fraud Recovery\"\",\"\"Total Fraud Loss\"\"]",
			"[\"\"64\"\",\"\"66\"\",\"\"68\"\",\"\"72\"\"]:[\"\"30+ (%) Lagged EOP Outstanding\"\",\"\"30+ (%) Coincident EOP Outstanding\"\",\"\"90+ (%) Coincident EOP Outstanding\"\",\"\"90+ (%) Lagged EOP Outstanding\"\"]",
			"[\"\"60\"\",\"\"70\"\"]:[\"\"30+ (%) Lagged Acc\"\",\"\"90+ (%) Lagged Acc\"\"]",
			"[\"\"411\"\",\"\"412\"\"]:[\"\"Total # Write Off\"\",\"\"Total Write Off Amount\"\"]",
			"[\"\"444\"\",\"\"448\"\"]:[\"\"Total Fraud Write-Off Amount\"\",\"\"Total Delinquent Write-Off Amount\"\"]",
			"[\"\"929\"\",\"\"932\"\"]:[\"\"# Collateral Units\"\",\"\"Original Value of Collateral Units\"\"]",
			"[\"\"50\"\",\"\"952\"\"]:[\"\"# Accounts\"\",\"\"EOP Outstanding\"\"]",
			"[\"\"936\"\",\"\"940\"\"]:[\"\"# Collateral Units Repossessed\"\",\"\"Value of Collateral Units Repossessed\"\"]",
			"[\"\"340\"\",\"\"341\"\"]:[\"\"Total Interest Income\"\",\"\"Total Interest Income to Total Outstanding\"\"]",
			"[\"\"340\"\",\"\"344\"\"]:[\"\"Total Interest Income\"\",\"\"Total Revenue\"\"]",
			"[\"\"131\"\",\"\"139\"\",\"\"147\"\",\"\"155\"\",\"\"163\"\",\"\"171\"\",\"\"179\"\",\"\"187\"\",\"\"195\"\",\"\"203\"\",\"\"211\"\",\"\"219\"\",\"\"227\"\"]:[\"\"EOP Outstanding Roll Forward (0 TO 1)\"\",\"\"EOP Outstanding Roll Forward (1 TO 2)\"\",\"\"EOP Outstanding Roll Forward (2 TO 3)\"\",\"\"EOP Outstanding Roll Forward (3 TO 4)\"\",\"\"EOP Outstanding Roll Forward (4 TO 5)\"\",\"\"EOP Outstanding Roll Forward (5 TO 6)\"\",\"\"EOP Outstanding Roll Forward (6 TO 7)\"\",\"\"EOP Outstanding Roll Forward (7 TO 8)\"\",\"\"EOP Outstanding Roll Forward (8 TO 9)\"\",\"\"EOP Outstanding Roll Forward (9 TO 10)\"\",\"\"EOP Outstanding Roll Forward (10 TO 11)\"\",\"\"EOP Outstanding Roll Forward (11 TO 12)\"\",\"\"EOP Outstanding Roll Forward (12 TO 13)\"\"]",
			"[\"\"127\"\",\"\"135\"\",\"\"143\"\",\"\"151\"\",\"\"159\"\",\"\"167\"\",\"\"175\"\",\"\"183\"\",\"\"191\"\",\"\"199\"\",\"\"207\"\",\"\"215\"\",\"\"223\"\"]:[\"\"Accounts Roll Forward (Bucket 0)\"\",\"\"Accounts Roll Forward (Bucket 1)\"\",\"\"Accounts Roll Forward (Bucket 2)\"\",\"\"Accounts Roll Forward (Bucket 3)\"\",\"\"Accounts Roll Forward (Bucket 4)\"\",\"\"Accounts Roll Forward (Bucket 5)\"\",\"\"Accounts Roll Forward (Bucket 6)\"\",\"\"Accounts Roll Forward (Bucket 7)\"\",\"\"Accounts Roll Forward (Bucket 8)\"\",\"\"Accounts Roll Forward (Bucket 9)\"\",\"\"Accounts Roll Forward (Bucket 10)\"\",\"\"Accounts Roll Forward (Bucket 11)\"\",\"\"Accounts Roll Forward (Bucket 12)\"\"]",
			"[\"\"130\"\",\"\"138\"\",\"\"146\"\",\"\"154\"\",\"\"162\"\",\"\"170\"\",\"\"178\"\",\"\"186\"\",\"\"194\"\",\"\"202\"\",\"\"210\"\",\"\"218\"\",\"\"226\"\"]:[\"\"EOP Outstanding Roll Back (1 TO 0)\"\",\"\"EOP Outstanding Roll Back (2 TO 1)\"\",\"\"EOP Outstanding Roll Back (3 TO 2)\"\",\"\"EOP Outstanding Roll Back (4 TO 3)\"\",\"\"EOP Outstanding Roll Back (5 TO 4)\"\",\"\"EOP Outstanding Roll Back (6 TO 5)\"\",\"\"EOP Outstanding Roll Back (7 TO 6)\"\",\"\"EOP Outstanding Roll Back (8 TO 7)\"\",\"\"EOP Outstanding Roll Back (9 TO 8)\"\",\"\"EOP Outstanding Roll Back (10 TO 9)\"\",\"\"EOP Outstanding Roll Back (11 TO 10)\"\",\"\"EOP Outstanding Roll Back (12 TO 11)\"\",\"\"EOP Outstanding Roll Back (13 TO 12)\"\"]",
			"[\"\"126\"\",\"\"134\"\",\"\"142\"\",\"\"150\"\",\"\"158\"\",\"\"166\"\",\"\"174\"\",\"\"182\"\",\"\"190\"\",\"\"198\"\",\"\"206\"\",\"\"214\"\",\"\"222\"\"]:[\"\"Accounts Roll Back (1 TO 0)\"\",\"\"Accounts Roll Back (2 TO 1)\"\",\"\"Accounts Roll Back (3 TO 2)\"\",\"\"Accounts Roll Back (4 TO 3)\"\",\"\"Accounts Roll Back (5 TO 4)\"\",\"\"Accounts Roll Back (6 TO 5)\"\",\"\"Accounts Roll Back (7 TO 6)\"\",\"\"Accounts Roll Back (8 TO 7)\"\",\"\"Accounts Roll Back (9 TO 8)\"\",\"\"Accounts Roll Back (10 TO 9)\"\",\"\"Accounts Roll Back (11 TO 10)\"\",\"\"Accounts Roll Back (12 TO 11)\"\",\"\"Accounts Roll Back (13 TO 12)\"\"]",
			"[\"\"132\"\",\"\"140\"\",\"\"148\"\",\"\"156\"\",\"\"164\"\",\"\"172\"\",\"\"180\"\",\"\"188\"\",\"\"196\"\",\"\"204\"\",\"\"212\"\",\"\"220\"\",\"\"228\"\"]:[\"\"EOP Outstanding Stabilized Rate (0 TO 0)\"\",\"\"EOP Outstanding Stabilized Rate (1 TO 1)\"\",\"\"EOP Outstanding Stabilized Rate (2 TO 2)\"\",\"\"EOP Outstanding Stabilized Rate (3 TO 3)\"\",\"\"EOP Outstanding Stabilized Rate (4 TO 4)\"\",\"\"EOP Outstanding Stabilized Rate (5 TO 5)\"\",\"\"EOP Outstanding Stabilized Rate (6 TO 6)\"\",\"\"EOP Outstanding Stabilized Rate (7 TO 7)\"\",\"\"EOP Outstanding Stabilized Rate (8 TO 8)\"\",\"\"EOP Outstanding Stabilized Rate (9 TO 9)\"\",\"\"EOP Outstanding Stabilized Rate (10 TO 10)\"\",\"\"EOP Outstanding Stabilized Rate (11 TO 11)\"\",\"\"EOP Outstanding Stabilized Rate (12 TO 12)\"\"]",
			"[\"\"128\"\",\"\"136\"\",\"\"144\"\",\"\"152\"\",\"\"160\"\",\"\"168\"\",\"\"176\"\",\"\"184\"\",\"\"192\"\",\"\"200\"\",\"\"208\"\",\"\"216\"\",\"\"224\"\"]:[\"\"Accounts Stabilized Rate (0 TO 0)\"\",\"\"Accounts Stabilized Rate (1 TO 1)\"\",\"\"Accounts Stabilized Rate (2 TO 2)\"\",\"\"Accounts Stabilized Rate (3 TO 3)\"\",\"\"Accounts Stabilized Rate (4 TO 4)\"\",\"\"Accounts Stabilized Rate (5 TO 5)\"\",\"\"Accounts Stabilized Rate (6 TO 6)\"\",\"\"Accounts Stabilized Rate (7 TO 7)\"\",\"\"Accounts Stabilized Rate (8 TO 8)\"\",\"\"Accounts Stabilized Rate (9 TO 9)\"\",\"\"Accounts Stabilized Rate (10 TO 10)\"\",\"\"Accounts Stabilized Rate (11 TO 11)\"\",\"\"Accounts Stabilized Rate (12 TO 12)\"\"]",
			"[\"\"129\"\",\"\"137\"\",\"\"145\"\",\"\"153\"\",\"\"161\"\",\"\"169\"\",\"\"177\"\",\"\"185\"\",\"\"193\"\",\"\"201\"\",\"\"209\"\",\"\"217\"\",\"\"225\"\"]:[\"\"EOP Outstanding Normalized (1 TO 0)\"\",\"\"EOP Outstanding Normalized (2 TO 0)\"\",\"\"EOP Outstanding Normalized (3 TO 0)\"\",\"\"EOP Outstanding Normalized (4 TO 0)\"\",\"\"EOP Outstanding Normalized (5 TO 0)\"\",\"\"EOP Outstanding Normalized (6 TO 0)\"\",\"\"EOP Outstanding Normalized (7 TO 0)\"\",\"\"EOP Outstanding Normalized (8 TO 0)\"\",\"\"EOP Outstanding Normalized (9 TO 0)\"\",\"\"EOP Outstanding Normalized (10 TO 0)\"\",\"\"EOP Outstanding Normalized (11 TO 0)\"\",\"\"EOP Outstanding Normalized (12 TO 0)\"\",\"\"EOP Outstanding Normalized (13 TO 0)\"\"]",
			"[\"\"125\"\",\"\"133\"\",\"\"141\"\",\"\"149\"\",\"\"157\"\",\"\"165\"\",\"\"173\"\",\"\"181\"\",\"\"189\"\",\"\"197\"\",\"\"205\"\",\"\"213\"\",\"\"221\"\"]:[\"\"Accounts Normalized (1 TO 0)\"\",\"\"Accounts Normalized (2 TO 0)\"\",\"\"Accounts Normalized (3 TO 0)\"\",\"\"Accounts Normalized (4 TO 0)\"\",\"\"Accounts Normalized (5 TO 0)\"\",\"\"Accounts Normalized (6 TO 0)\"\",\"\"Accounts Normalized (7 TO 0)\"\",\"\"Accounts Normalized (8 To 0)\"\",\"\"Accounts Normalized (9 TO 0)\"\",\"\"Accounts Normalized (10 TO 0)\"\",\"\"Accounts Normalized (11 TO 0)\"\",\"\"Accounts Normalized (12 TO 0)\"\",\"\"Accounts Normalized (13 TO 0)\"\"]",
			"[\"\"229\"\",\"\"231\"\",\"\"233\"\",\"\"235\"\",\"\"237\"\",\"\"617\"\",\"\"241\"\",\"\"243\"\"]:[\"\"EOP Accounts Net Flow Rate (0 TO 1)\"\",\"\"EOP Accounts Net Flow Rate (1 TO 2)\"\",\"\"EOP Accounts Net Flow Rate (2 TO 3)\"\",\"\"EOP Accounts Net Flow Rate (3 TO 4)\"\",\"\"EOP Accounts Net Flow Rate (4 TO 5)\"\",\"\"EOP Accounts Net Flow Rate (5 TO 6)\"\",\"\"EOP Accounts Net Flow Rate (6 TO 7)\"\",\"\"EOP Accounts Net Flow Rate (7 TO 8)\"\"]",
			"[\"\"230\"\",\"\"232\"\",\"\"234\"\",\"\"236\"\",\"\"238\"\",\"\"239\"\",\"\"242\"\",\"\"244\"\"]:[\"\"EOP Outstanding Net Flow Rate (0 TO 1)\"\",\"\"EOP Outstanding Net Flow Rate (1 TO 2)\"\",\"\"EOP Outstanding Net Flow Rate (2 TO 3)\"\",\"\"EOP Outstanding Net Flow Rate (3 TO 4)\"\",\"\"EOP Outstanding Net Flow Rate (4 TO 5)\"\",\"\"EOP Outstanding Net Flow Rate (5 TO 6)\"\",\"\"EOP Outstanding Net Flow Rate (6 TO 7)\"\",\"\"EOP Outstanding Net Flow Rate (7 TO 8)\"\"]",
			"[\"\"131\"\",\"\"139\"\",\"\"147\"\",\"\"155\"\",\"\"163\"\",\"\"171\"\",\"\"179\"\",\"\"187\"\",\"\"195\"\",\"\"203\"\",\"\"211\"\",\"\"219\"\",\"\"227\"\"]:[\"\"EOP Outstanding Roll Forward (0 TO 1)\"\",\"\"EOP Outstanding Roll Forward (1 TO 2)\"\",\"\"EOP Outstanding Roll Forward (2 TO 3)\"\",\"\"EOP Outstanding Roll Forward (3 TO 4)\"\",\"\"EOP Outstanding Roll Forward (4 TO 5)\"\",\"\"EOP Outstanding Roll Forward (5 TO 6)\"\",\"\"EOP Outstanding Roll Forward (6 TO 7)\"\",\"\"EOP Outstanding Roll Forward (7 TO 8)\"\",\"\"EOP Outstanding Roll Forward (8 TO 9)\"\",\"\"EOP Outstanding Roll Forward (9 TO 10)\"\",\"\"EOP Outstanding Roll Forward (10 TO 11)\"\",\"\"EOP Outstanding Roll Forward (11 TO 12)\"\",\"\"EOP Outstanding Roll Forward (12 TO 13)\"\"]",
			"[\"\"127\"\",\"\"135\"\",\"\"143\"\",\"\"151\"\",\"\"159\"\",\"\"167\"\",\"\"175\"\",\"\"183\"\",\"\"191\"\",\"\"199\"\",\"\"207\"\",\"\"215\"\",\"\"223\"\"]:[\"\"Accounts Worsen (0)\"\",\"\"Accounts Worsen (1)\"\",\"\"Accounts Worsen (2)\"\",\"\"Accounts Worsen (3)\"\",\"\"Accounts Worsen (4)\"\",\"\"Accounts Worsen (5)\"\",\"\"Accounts Worsen (6)\"\",\"\"Accounts Worsen (7)\"\",\"\"Accounts Worsen (8)\"\",\"\"Accounts Worsen (9)\"\",\"\"Accounts Worsen (10)\"\",\"\"Accounts Worsen (11)\"\",\"\"Accounts Worsen (12)\"\"]",
			"[\"\"130\"\",\"\"138\"\",\"\"146\"\",\"\"154\"\",\"\"162\"\",\"\"170\"\",\"\"178\"\",\"\"186\"\",\"\"194\"\",\"\"202\"\",\"\"210\"\",\"\"218\"\",\"\"226\"\"]:[\"\"EOP Outstanding Roll Back (1 TO 0)\"\",\"\"EOP Outstanding Roll Back (2 TO 1)\"\",\"\"EOP Outstanding Roll Back (3 TO 2)\"\",\"\"EOP Outstanding Roll Back (4 TO 3)\"\",\"\"EOP Outstanding Roll Back (5 TO 4)\"\",\"\"EOP Outstanding Roll Back (6 TO 5)\"\",\"\"EOP Outstanding Roll Back (7 TO 6)\"\",\"\"EOP Outstanding Roll Back (8 TO 7)\"\",\"\"EOP Outstanding Roll Back (9 TO 8)\"\",\"\"EOP Outstanding Roll Back (10 TO 9)\"\",\"\"EOP Outstanding Roll Back (11 TO 10)\"\",\"\"EOP Outstanding Roll Back (12 TO 11)\"\",\"\"EOP Outstanding Roll Back (13 TO 12)\"\"]",
			"[\"\"126\"\",\"\"134\"\",\"\"142\"\",\"\"150\"\",\"\"158\"\",\"\"166\"\",\"\"174\"\",\"\"182\"\",\"\"190\"\",\"\"198\"\",\"\"206\"\",\"\"214\"\",\"\"222\"\"]:[\"\"Accounts Roll Back (1 TO 0)\"\",\"\"Accounts Roll Back (2 TO 1)\"\",\"\"Accounts Roll Back (3 TO 2)\"\",\"\"Accounts Roll Back (4 TO 3)\"\",\"\"Accounts Roll Back (5 TO 4)\"\",\"\"Accounts Roll Back (6 TO 5)\"\",\"\"Accounts Roll Back (7 TO 6)\"\",\"\"Accounts Roll Back (8 TO 7)\"\",\"\"Accounts Roll Back (9 TO 8)\"\",\"\"Accounts Roll Back (10 TO 9)\"\",\"\"Accounts Roll Back (11 TO 10)\"\",\"\"Accounts Roll Back (12 TO 11)\"\",\"\"Accounts Roll Back (13 TO 12)\"\"]",
			"[\"\"132\"\",\"\"140\"\",\"\"148\"\",\"\"156\"\",\"\"164\"\",\"\"172\"\",\"\"180\"\",\"\"188\"\",\"\"196\"\",\"\"204\"\",\"\"212\"\",\"\"220\"\",\"\"228\"\"]:[\"\"EOP Outstanding Stabilized Rate (0 TO 0)\"\",\"\"EOP Outstanding Stabilized Rate (1 TO 1)\"\",\"\"EOP Outstanding Stabilized Rate (2 TO 2)\"\",\"\"EOP Outstanding Stabilized Rate (3 TO 3)\"\",\"\"EOP Outstanding Stabilized Rate (4 TO 4)\"\",\"\"EOP Outstanding Stabilized Rate (5 TO 5)\"\",\"\"EOP Outstanding Stabilized Rate (6 TO 6)\"\",\"\"EOP Outstanding Stabilized Rate (7 TO 7)\"\",\"\"EOP Outstanding Stabilized Rate (8 TO 8)\"\",\"\"EOP Outstanding Stabilized Rate (9 TO 9)\"\",\"\"EOP Outstanding Stabilized Rate (10 TO 10)\"\",\"\"EOP Outstanding Stabilized Rate (11 TO 11)\"\",\"\"EOP Outstanding Stabilized Rate (12 TO 12)\"\"]",
			"[\"\"128\"\",\"\"136\"\",\"\"144\"\",\"\"152\"\",\"\"160\"\",\"\"168\"\",\"\"176\"\",\"\"184\"\",\"\"192\"\",\"\"200\"\",\"\"208\"\",\"\"216\"\",\"\"224\"\"]:[\"\"Accounts Stabilized Rate (0 TO 0)\"\",\"\"Accounts Stabilized Rate (1 TO 1)\"\",\"\"Accounts Stabilized Rate (2 TO 2)\"\",\"\"Accounts Stabilized Rate (3 TO 3)\"\",\"\"Accounts Stabilized Rate (4 TO 4)\"\",\"\"Accounts Stabilized Rate (5 TO 5)\"\",\"\"Accounts Stabilized Rate (6 TO 6)\"\",\"\"Accounts Stabilized Rate (7 TO 7)\"\",\"\"Accounts Stabilized Rate (8 TO 8)\"\",\"\"Accounts Stabilized Rate (9 TO 9)\"\",\"\"Accounts Stabilized Rate (10 TO 10)\"\",\"\"Accounts Stabilized Rate (11 TO 11)\"\",\"\"Accounts Stabilized Rate (12 TO 12)\"\"]",
			"[\"\"131\"\",\"\"139\"\",\"\"147\"\",\"\"155\"\",\"\"163\"\",\"\"171\"\",\"\"179\"\",\"\"187\"\",\"\"195\"\",\"\"203\"\",\"\"211\"\",\"\"219\"\",\"\"227\"\"]:[\"\"EOP Outstanding Roll Forward (Bucket 0)\"\",\"\"EOP Outstanding Roll Forward (Bucket 1)\"\",\"\"EOP Outstanding Roll Forward (Bucket 2)\"\",\"\"EOP Outstanding Roll Forward (Bucket 3)\"\",\"\"EOP Outstanding Roll Forward (Bucket 4)\"\",\"\"EOP Outstanding Roll Forward (Bucket 5)\"\",\"\"EOP Outstanding Roll Forward (Bucket 6)\"\",\"\"EOP Outstanding Roll Forward (Bucket 7)\"\",\"\"EOP Outstanding Roll Forward (Bucket 8)\"\",\"\"EOP Outstanding Roll Forward (Bucket 9)\"\",\"\"EOP Outstanding Roll Forward (Bucket 10)\"\",\"\"EOP Outstanding Roll Forward (Bucket 11)\"\",\"\"EOP Outstanding Roll Forward (Bucket 12)\"\"]",
			"[\"\"127\"\",\"\"135\"\",\"\"143\"\",\"\"151\"\",\"\"159\"\",\"\"167\"\",\"\"175\"\",\"\"183\"\",\"\"191\"\",\"\"199\"\",\"\"207\"\",\"\"215\"\",\"\"223\"\"]:[\"\"Accounts Roll Forward (Bucket 0)\"\",\"\"Accounts Roll Forward (Bucket 1)\"\",\"\"Accounts Roll Forward (Bucket 2)\"\",\"\"Accounts Roll Forward (Bucket 3)\"\",\"\"Accounts Roll Forward (Bucket 4)\"\",\"\"Accounts Roll Forward (Bucket 5)\"\",\"\"Accounts Roll Forward (Bucket 6)\"\",\"\"Accounts Roll Forward (Bucket 7)\"\",\"\"Accounts Roll Forward (Bucket 8)\"\",\"\"Accounts Roll Forward (Bucket 9)\"\",\"\"Accounts Roll Forward (Bucket 10)\"\",\"\"Accounts Roll Forward (Bucket 11)\"\",\"\"Accounts Roll Forward (Bucket 12)\"\"]",
			"[\"\"130\"\",\"\"138\"\",\"\"146\"\",\"\"154\"\",\"\"162\"\",\"\"170\"\",\"\"178\"\",\"\"186\"\",\"\"194\"\",\"\"202\"\",\"\"210\"\",\"\"218\"\",\"\"226\"\"]:[\"\"EOP Outstanding Roll Back (Bucket 1)\"\",\"\"EOP Outstanding Roll Back (Bucket 2)\"\",\"\"EOP Outstanding Roll Back (Bucket 3)\"\",\"\"EOP Outstanding Roll Back (Bucket 4)\"\",\"\"EOP Outstanding Roll Back (Bucket 5)\"\",\"\"EOP Outstanding Roll Back (Bucket 6)\"\",\"\"EOP Outstanding Roll Back (Bucket 7)\"\",\"\"EOP Outstanding Roll Back (Bucket 8)\"\",\"\"EOP Outstanding Roll Back (Bucket 9)\"\",\"\"EOP Outstanding Roll Back (Bucket 10)\"\",\"\"EOP Outstanding Roll Back (Bucket 11)\"\",\"\"EOP Outstanding Roll Back (Bucket 12)\"\",\"\"EOP Outstanding Roll Back (Bucket 13)\"\"]",
			"[\"\"126\"\",\"\"134\"\",\"\"142\"\",\"\"150\"\",\"\"158\"\",\"\"166\"\",\"\"174\"\",\"\"182\"\",\"\"190\"\",\"\"198\"\",\"\"206\"\",\"\"214\"\",\"\"222\"\"]:[\"\"Accounts Roll Back (Bucket 1)\"\",\"\"Accounts Roll Back (Bucket 2)\"\",\"\"Accounts Roll Back (Bucket 3)\"\",\"\"Accounts Roll Back (Bucket 4)\"\",\"\"Accounts Roll Back (Bucket 5)\"\",\"\"Accounts Roll Back (Bucket 6)\"\",\"\"Accounts Roll Back (Bucket 7)\"\",\"\"Accounts Roll Back (Bucket 8)\"\",\"\"Accounts Roll Back (Bucket 9)\"\",\"\"Accounts Roll Back (Bucket 10)\"\",\"\"Accounts Roll Back (Bucket 11)\"\",\"\"Accounts Roll Back (Bucket 12)\"\",\"\"Accounts Roll Back (Bucket 13)\"\"]",
			"[\"\"132\"\",\"\"140\"\",\"\"148\"\",\"\"156\"\",\"\"164\"\",\"\"172\"\",\"\"180\"\",\"\"188\"\",\"\"196\"\",\"\"204\"\",\"\"212\"\",\"\"220\"\",\"\"228\"\"]:[\"\"EOP Outstanding Stabilized Rate (Bucket 0)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 1)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 2)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 3)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 4)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 5)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 6)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 7)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 8)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 9)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 10)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 11)\"\",\"\"EOP Outstanding Stabilized Rate (Bucket 12)\"\"]",
			"[\"\"128\"\",\"\"136\"\",\"\"144\"\",\"\"152\"\",\"\"160\"\",\"\"168\"\",\"\"176\"\",\"\"184\"\",\"\"192\"\",\"\"200\"\",\"\"208\"\",\"\"216\"\",\"\"224\"\"]:[\"\"Accounts Stabilized Rate (Bucket 0)\"\",\"\"Accounts Stabilized Rate (Bucket 1)\"\",\"\"Accounts Stabilized Rate (Bucket 2)\"\",\"\"Accounts Stabilized Rate (Bucket 3)\"\",\"\"Accounts Stabilized Rate (Bucket 4)\"\",\"\"Accounts Stabilized Rate (Bucket 5)\"\",\"\"Accounts Stabilized Rate (Bucket 6)\"\",\"\"Accounts Stabilized Rate (Bucket 7)\"\",\"\"Accounts Stabilized Rate (Bucket 8)\"\",\"\"Accounts Stabilized Rate (Bucket 9)\"\",\"\"Accounts Stabilized Rate (Bucket 10)\"\",\"\"Accounts Stabilized Rate (Bucket 11)\"\",\"\"Accounts Stabilized Rate (Bucket 12)\"\"]",
			"[\"\"129\"\",\"\"137\"\",\"\"145\"\",\"\"153\"\",\"\"161\"\",\"\"169\"\",\"\"177\"\",\"\"185\"\",\"\"193\"\",\"\"201\"\",\"\"209\"\",\"\"217\"\",\"\"225\"\"]:[\"\"EOP Outstanding Normalized (Bucket 1)\"\",\"\"EOP Outstanding Normalized (Bucket 2)\"\",\"\"EOP Outstanding Normalized (Bucket 3)\"\",\"\"EOP Outstanding Normalized (Bucket 4)\"\",\"\"EOP Outstanding Normalized (Bucket 5)\"\",\"\"EOP Outstanding Normalized (Bucket 6)\"\",\"\"EOP Outstanding Normalized (Bucket 7)\"\",\"\"EOP Outstanding Normalized (Bucket 8)\"\",\"\"EOP Outstanding Normalized (Bucket 9)\"\",\"\"EOP Outstanding Normalized (Bucket 10)\"\",\"\"EOP Outstanding Normalized (Bucket 11)\"\",\"\"EOP Outstanding Normalized (Bucket 12)\"\",\"\"EOP Outstanding Normalized (Bucket 13)\"\"]",
			"[\"\"125\"\",\"\"133\"\",\"\"141\"\",\"\"149\"\",\"\"157\"\",\"\"165\"\",\"\"173\"\",\"\"181\"\",\"\"189\"\",\"\"197\"\",\"\"205\"\",\"\"213\"\",\"\"221\"\"]:[\"\"Accounts Normalized (Bucket 1)\"\",\"\"Accounts Normalized (Bucket 2)\"\",\"\"Accounts Normalized (Bucket 3)\"\",\"\"Accounts Normalized (Bucket 4)\"\",\"\"Accounts Normalized (Bucket 5)\"\",\"\"Accounts Normalized (Bucket 6)\"\",\"\"Accounts Normalized (Bucket 7)\"\",\"\"Accounts Normalized (Bucket 8)\"\",\"\"Accounts Normalized (Bucket 9)\"\",\"\"Accounts Normalized (Bucket 10)\"\",\"\"Accounts Normalized (Bucket 11)\"\",\"\"Accounts Normalized (Bucket 12)\"\",\"\"Accounts Normalized (Bucket 13)\"\"]",
			"[\"\"131\"\",\"\"139\"\",\"\"147\"\",\"\"155\"\",\"\"163\"\",\"\"171\"\",\"\"179\"\",\"\"187\"\",\"\"195\"\",\"\"203\"\",\"\"211\"\",\"\"219\"\",\"\"227\"\"]:[\"\"Outstanding Worsen (0)\"\",\"\"Outstanding Worsen (1)\"\",\"\"Outstanding Worsen (2)\"\",\"\"Outstanding Worsen (3)\"\",\"\"Outstanding Worsen (4)\"\",\"\"Outstanding Worsen (5)\"\",\"\"Outstanding Worsen (6)\"\",\"\"Outstanding Worsen (7)\"\",\"\"Outstanding Worsen (8)\"\",\"\"Outstanding Worsen (9)\"\",\"\"Outstanding Worsen (10)\"\",\"\"Outstanding Worsen (11)\"\",\"\"Outstanding Worsen (12)\"\"]",
			"[\"\"127\"\",\"\"135\"\",\"\"143\"\",\"\"151\"\",\"\"159\"\",\"\"167\"\",\"\"175\"\",\"\"183\"\",\"\"191\"\",\"\"199\"\",\"\"207\"\",\"\"215\"\",\"\"223\"\"]:[\"\"Accounts Worsen (0)\"\",\"\"Accounts Worsen (1)\"\",\"\"Accounts Worsen (2)\"\",\"\"Accounts Worsen (3)\"\",\"\"Accounts Worsen (4)\"\",\"\"Accounts Worsen (5)\"\",\"\"Accounts Worsen (6)\"\",\"\"Accounts Worsen (7)\"\",\"\"Accounts Worsen (8)\"\",\"\"Accounts Worsen (9)\"\",\"\"Accounts Worsen (10)\"\",\"\"Accounts Worsen (11)\"\",\"\"Accounts Worsen (12)\"\"]",
			"[\"\"130\"\",\"\"138\"\",\"\"146\"\",\"\"154\"\",\"\"162\"\",\"\"170\"\",\"\"178\"\",\"\"186\"\",\"\"194\"\",\"\"202\"\",\"\"210\"\",\"\"218\"\",\"\"226\"\"]:[\"\"Outstanding Improve (1)\"\",\"\"Outstanding Improve (2)\"\",\"\"Outstanding Improve (3)\"\",\"\"Outstanding Improve (4)\"\",\"\"Outstanding Improve (5)\"\",\"\"Outstanding Improve (6)\"\",\"\"Outstanding Improve (7)\"\",\"\"Outstanding Improve (8)\"\",\"\"Outstanding Improve (9)\"\",\"\"Outstanding Improve (10)\"\",\"\"Outstanding Improve (11)\"\",\"\"Outstanding Improve (12)\"\",\"\"Outstanding Improve (13)\"\"]",
			"[\"\"126\"\",\"\"134\"\",\"\"142\"\",\"\"150\"\",\"\"158\"\",\"\"166\"\",\"\"174\"\",\"\"182\"\",\"\"190\"\",\"\"198\"\",\"\"206\"\",\"\"214\"\",\"\"222\"\"]:[\"\"Accounts Improve (1)\"\",\"\"Accounts Improve (2)\"\",\"\"Accounts Improve (3)\"\",\"\"Accounts Improve (4)\"\",\"\"Accounts Improve (5)\"\",\"\"Accounts Improve (6)\"\",\"\"Accounts Improve (7)\"\",\"\"Accounts Improve (8)\"\",\"\"Accounts Improve (9)\"\",\"\"Accounts Improve (10)\"\",\"\"Accounts Improve (11)\"\",\"\"Accounts Improve (12)\"\",\"\"Accounts Improve (13)\"\"]",
			"[\"\"132\"\",\"\"140\"\",\"\"148\"\",\"\"156\"\",\"\"164\"\",\"\"172\"\",\"\"180\"\",\"\"188\"\",\"\"196\"\",\"\"204\"\",\"\"212\"\",\"\"220\"\",\"\"228\"\"]:[\"\"Outstanding Hold (0)\"\",\"\"Outstanding Hold (1)\"\",\"\"Outstanding Hold (2)\"\",\"\"Outstanding Hold (3)\"\",\"\"Outstanding Hold (4)\"\",\"\"Outstanding Hold (5)\"\",\"\"Outstanding Hold (6)\"\",\"\"Outstanding Hold (7)\"\",\"\"Outstanding Hold (8)\"\",\"\"Outstanding Hold (9)\"\",\"\"Outstanding Hold (10)\"\",\"\"Outstanding Hold (11)\"\",\"\"Outstanding Hold (12)\"\"]",
			"[\"\"128\"\",\"\"136\"\",\"\"144\"\",\"\"152\"\",\"\"160\"\",\"\"168\"\",\"\"176\"\",\"\"184\"\",\"\"192\"\",\"\"200\"\",\"\"208\"\",\"\"216\"\",\"\"224\"\"]:[\"\"Accounts Hold (0)\"\",\"\"Accounts Hold (1)\"\",\"\"Accounts Hold (2)\"\",\"\"Accounts Hold (3)\"\",\"\"Accounts Hold (4)\"\",\"\"Accounts Hold (5)\"\",\"\"Accounts Hold (6)\"\",\"\"Accounts Hold (7)\"\",\"\"Accounts Hold (8)\"\",\"\"Accounts Hold (9)\"\",\"\"Accounts Hold (10)\"\",\"\"Accounts Hold (11)\"\",\"\"Accounts Hold (12)\"\"]",
			"[\"\"388\"\",\"\"1\"\"]:[\"\"EOP Total Overdue\"\",\"\"# New Accounts\"\"]",
			"[\"\"502\"\",\"\"503\"\",\"\"519\"\"]:[\"\"# Cash Sales\"\",\"\"Amount Cash Sales\"\",\"\"# Retail Sales\"\"]",
			"[\"\"549\"\",\"\"551\"\",\"\"607\"\"]:[\"\"# 30+ Delinquent Accounts\"\",\"\"# 90+ Delinquent Accounts\"\",\"\"# 60 + % Coincident Accounts\"\"]",
			"[\"\"1057\"\"]:[\"\"Rejected Apps %\"\"]",
			"[\"\"379\"\",\"\"1407\"\"]:[\"\"EOP Outstanding\"\",\"\"ENR %\"\"]",
			"[\"\"79\"\",\"\"344\"\"]:[\"\"Revenue % ANR\"\",\"\"Total Revenue\"\"]",
			"[\"\"1036\"\"]:[\"\"% Ever 30 DPD Outstanding\"\"]",
			"[\"\"1037\"\"]:[\"\"% Ever 90 DPD Outstanding\"\"]",
			"[\"\"9\"\"]:[\"\"# Approvals Received\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"379\"\"]:[\"\"EOP Outstanding\"\"]",
			"[\"\"379\"\"]:[\"\"EOP Outstanding\"\"]",
			"[\"\"382\"\",\"\"383\"\",\"\"384\"\"]:[\"\"Total Outstanding Fees\"\",\"\"Total Outstanding Interest\"\",\"\"Total Outstanding Principal\"\"]",
			"[\"\"50\"\",\"\"55\"\",\"\"951\"\"]:[\"\"# Total Accounts\"\",\"\"Avg. Loan Size\"\",\"\"EOP Outstanding\"\"]",
			"[\"\"50\"\",\"\"55\"\",\"\"951\"\"]:[\"\"# Total Accounts\"\",\"\"Avg. Loan Size\"\",\"\"EOP Outstanding\"\"]",
			"[\"\"50\"\",\"\"55\"\",\"\"951\"\"]:[\"\"# Total Accounts\"\",\"\"Avg. Loan Size\"\",\"\"EOP Outstanding\"\"]",
			"[\"\"50\"\",\"\"55\"\",\"\"951\"\"]:[\"\"# Total Accounts\"\",\"\"Avg. Loan Size\"\",\"\"EOP Outstanding\"\"]",
			"[\"\"1046\"\",\"\"1048\"\"]:[\"\"# Write-Off Accounts\"\",\"\"Total Write-Off Amount\"\"]",
			"[\"\"952\"\",\"\"1408\"\"]:[\"\"Total Outstanding\"\",\"\"ENR %\"\"]",
			"[\"\"944\"\",\"\"947\"\"]:[\"\"30 + % Lagged EOP Outstanding\"\",\"\"90 + % Lagged EOP Outstanding\"\"]",
			"[\"\"50\"\",\"\"55\"\",\"\"951\"\"]:[\"\"# Accounts\"\",\"\"Avg Loan Size\"\",\"\"EOP Total Outstanding\"\"]",
			"[\"\"133\"\",\"\"141\"\",\"\"149\"\",\"\"157\"\",\"\"165\"\",\"\"173\"\"]:[\"\"Accounts Normalized (Bucket 2)\"\",\"\"Accounts Normalized (Bucket 3)\"\",\"\"Accounts Normalized (Bucket 4)\"\",\"\"Accounts Normalized (Bucket 5)\"\",\"\"Accounts Normalized (Bucket 6)\"\",\"\"Accounts Normalized (Bucket 7)\"\"]",
			"[\"\"50\"\",\"\"381\"\",\"\"390\"\"]:[\"\"# Accounts\"\",\"\"ANR\"\",\"\"Total Payments\"\"]",
			"[\"\"344\"\"]:[\"\"Total Revenue\"\"]",
			"[\"\"8\"\",\"\"9\"\"]:[\"\"# Apps Received\"\",\"\"# Approvals Received\"\"]",
			"[\"\"4\"\",\"\"635\"\"]:[\"\"Amount Booked\"\",\"\"# New Accounts\"\"]",
			"[\"\"960\"\"]:[\"\"Total Fraud Loss\"\"]",
			"[\"\"336\"\",\"\"429\"\",\"\"430\"\",\"\"341\"\"]:[\"\"Total Fee Income to Total Outstanding\"\",\"\"EOP Net Credit Loss Rate\"\",\"\"EOP Gross Credit Loss Rate\"\",\"\"Total Interest Income to Total Outstanding\"\"]",
			"[\"\"336\"\",\"\"429\"\",\"\"430\"\",\"\"341\"\"]:[\"\"Total Fee Income to Total Outstanding\"\",\"\"EOP Net Credit Loss Rate\"\",\"\"EOP Gross Credit Loss Rate\"\",\"\"Total Interest Income to Total Outstanding\"\"]",
			"[\"\"344\"\"]:[\"\"Total Revenue\"\"]",
			"[\"\"8\"\",\"\"1056\"\"]:[\"\"# Apps Received\"\",\"\"# Apps Rejected\"\"]",
			"[\"\"4\"\"]:[\"\"Amount Booked\"\"]",
			"[\"\"16\"\",\"\"17\"\"]:[\"\"Approval Rate\"\",\"\"Decline Rate\"\"]",
			"[\"\"635\"\"]:[\"\"# New Accounts\"\"]",
			"[\"\"4\"\"]:[\"\"Amount Booked\"\"]",
			"[\"\"8\"\",\"\"9\"\",\"\"4\"\"]:[\"\"# Apps Received\"\",\"\"# Approvals Received\"\",\"\"Amount Booked\"\"]",
			"[\"\"21\"\"]:[\"\"# Total Exceptions\"\"]",
			"[\"\"1057\"\"]:[\"\"Rejected Apps %\"\"]",
			"[\"\"11\"\"]:[\"\"# Total Decisioned Applications\"\"]",
			"[\"\"984\"\"]:[\"\"Ever 90+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"635\"\",\"\"4\"\"]:[\"\"# New Accounts\"\",\"\"Amount Booked\"\"]",
			"[\"\"4\"\"]:[\"\"Amount Booked\"\"]",
			"[\"\"8\"\",\"\"9\"\",\"\"4\"\"]:[\"\"# Apps Received\"\",\"\"# Approvals Received\"\",\"\"Amount Booked\"\"]",
			"[\"\"9\"\"]:[\"\"# Approvals Received\"\"]",
			"[\"\"635\"\"]:[\"\"# New Accounts\"\"]",
			"[\"\"9\"\"]:[\"\"# Approvals Received\"\"]",
			"[\"\"1056\"\"]:[\"\"# Apps Rejected\"\"]",
			"[\"\"8\"\",\"\"1056\"\"]:[\"\"# Apps Received\"\",\"\"# Apps Rejected\"\"]",
			"[\"\"4\"\"]:[\"\"Amount Booked\"\"]",
			"[\"\"9\"\"]:[\"\"# Approvals Received\"\"]",
			"[\"\"16\"\"]:[\"\"Approval Rate\"\"]",
			"[\"\"4\"\"]:[\"\"Amount Booked\"\"]",
			"[\"\"16\"\",\"\"17\"\"]:[\"\"Approval Rate\"\",\"\"Decline Rate\"\"]",
			"[\"\"16\"\"]:[\"\"Approval Rate\"\"]",
			"[\"\"3755\"\"]:[\"\"90+ Coincident Outstanding (%)\"\"]",
			"[\"\"982\"\"]:[\"\"Ever 30+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"983\"\"]:[\"\"Ever 60+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"984\"\"]:[\"\"Ever 90+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"981\"\"]:[\"\"Ever 120+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"981\"\",\"\"982\"\",\"\"983\"\",\"\"984\"\"]:[\"\"Ever 120+ DPD Outstanding to Total Amount Booked\"\",\"\"Ever 30+ DPD Outstanding to Total Amount Booked\"\",\"\"Ever 60+ DPD Outstanding to Total Amount Booked\"\",\"\"Ever 90+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"3502\"\",\"\"3504\"\",\"\"3506\"\"]:[\"\"30+ (%) Coincident EOP Outstanding\"\",\"\"60+ (%) Coincident EOP Outstanding\"\",\"\"90+ (%) Coincident EOP Outstanding\"\"]",
			"[\"\"3510\"\",\"\"3511\"\"]:[\"\"GCL Amount\"\",\"\"GCL % ANR\"\"]",
			"[\"\"3514\"\",\"\"3515\"\",\"\"3516\"\",\"\"3517\"\",\"\"3518\"\",\"\"3519\"\",\"\"3520\"\",\"\"3521\"\"]:[\"\"Bucket 0\"\",\"\"Bucket 1\"\",\"\"Bucket 2\"\",\"\"Bucket 3\"\",\"\"Bucket 4\"\",\"\"Bucket 5\"\",\"\"Bucket 6\"\",\"\"Bucket 7\"\"]",
			"[\"\"3530\"\",\"\"3531\"\"]:[\"\"Delinquent to Total Accounts\"\",\"\"Non-Delinquent to Total Accounts\"\"]",
			"[\"\"3533\"\",\"\"3534\"\"]:[\"\"# 30+ Delinquent Accounts\"\",\"\"30+ Delinquent EOP Outstanding\"\"]",
			"[\"\"3539\"\",\"\"3540\"\",\"\"3541\"\"]:[\"\"EOP Total Outstanding\"\",\"\"EOP Delinquent Outstanding\"\",\"\"EOP Non-Delinquent Outstanding\"\"]",
			"[\"\"3545\"\",\"\"3546\"\"]:[\"\"# Fraud Write-Off Accounts\"\",\"\"Total Fraud Write-Off Amount\"\"]",
			"[\"\"3551\"\",\"\"3552\"\",\"\"3553\"\",\"\"3554\"\",\"\"3555\"\",\"\"3556\"\",\"\"3557\"\",\"\"3558\"\"]:[\"\"EOP Accounts Net Flow Rate (0 TO 1)\"\",\"\"EOP Accounts Net Flow Rate (1 TO 2)\"\",\"\"EOP Accounts Net Flow Rate (2 TO 3)\"\",\"\"EOP Accounts Net Flow Rate (3 TO 4)\"\",\"\"EOP Accounts Net Flow Rate (4 TO 5)\"\",\"\"EOP Accounts Net Flow Rate (5 TO 6)\"\",\"\"EOP Accounts Net Flow Rate (6 TO 7)\"\",\"\"EOP Accounts Net Flow Rate (7 TO 8)\"\"]",
			"[\"\"3563\"\",\"\"3564\"\",\"\"3565\"\",\"\"3566\"\",\"\"3567\"\",\"\"3568\"\",\"\"3569\"\",\"\"3570\"\"]:[\"\"EOP Outstanding Net Flow Rate (0 TO 1)\"\",\"\"EOP Outstanding Net Flow Rate (1 TO 2)\"\",\"\"EOP Outstanding Net Flow Rate (2 TO 3)\"\",\"\"EOP Outstanding Net Flow Rate (3 TO 4)\"\",\"\"EOP Outstanding Net Flow Rate (4 TO 5)\"\",\"\"EOP Outstanding Net Flow Rate (5 TO 6)\"\",\"\"EOP Outstanding Net Flow Rate (6 TO 7)\"\",\"\"EOP Outstanding Net Flow Rate (7 TO 8)\"\"]",
			"[\"\"3575\"\"]:[\"\"Total Payments\"\"]",
			"[\"\"3527\"\",\"\"3539\"\"]:[\"\"# Total Accounts\"\",\"\"EOP Total Outstanding\"\"]",
			"[\"\"3527\"\",\"\"3584\"\"]:[\"\"# Total Accounts\"\",\"\"ANR\"\"]",
			"[\"\"3585\"\",\"\"3586\"\",\"\"3587\"\"]:[\"\"Total Outstanding Fees\"\",\"\"Total Outstanding Interest\"\",\"\"Total Outstanding Principal\"\"]",
			"[\"\"3513\"\",\"\"3588\"\"]:[\"\"Total Write-Off Amount\"\",\"\"Total Amount Recovered\"\"]",
			"[\"\"3589\"\",\"\"3590\"\",\"\"3591\"\",\"\"3592\"\",\"\"3593\"\",\"\"3594\"\",\"\"3595\"\",\"\"3596\"\"]:[\"\"Accounts Normalized (Bucket 1)\"\",\"\"Accounts Normalized (Bucket 2)\"\",\"\"Accounts Normalized (Bucket 3)\"\",\"\"Accounts Normalized (Bucket 4)\"\",\"\"Accounts Normalized (Bucket 5)\"\",\"\"Accounts Normalized (Bucket 6)\"\",\"\"Accounts Normalized (Bucket 7)\"\",\"\"Accounts Normalized (Bucket 8)\"\"]",
			"[\"\"3602\"\",\"\"3603\"\",\"\"3604\"\",\"\"3605\"\",\"\"3606\"\",\"\"3607\"\",\"\"3608\"\",\"\"3609\"\"]:[\"\"Accounts Roll Back (Bucket 1)\"\",\"\"Accounts Roll Back (Bucket 2)\"\",\"\"Accounts Roll Back (Bucket 3)\"\",\"\"Accounts Roll Back (Bucket 4)\"\",\"\"Accounts Roll Back (Bucket 5)\"\",\"\"Accounts Roll Back (Bucket 6)\"\",\"\"Accounts Roll Back (Bucket 7)\"\",\"\"Accounts Roll Back (Bucket 8)\"\"]",
			"[\"\"3615\"\",\"\"3616\"\",\"\"3617\"\",\"\"3618\"\",\"\"3619\"\",\"\"3620\"\",\"\"3621\"\",\"\"3622\"\",\"\"3623\"\"]:[\"\"Accounts Roll Forward (Bucket 0)\"\",\"\"Accounts Roll Forward (Bucket 1)\"\",\"\"Accounts Roll Forward (Bucket 2)\"\",\"\"Accounts Roll Forward (Bucket 3)\"\",\"\"Accounts Roll Forward (Bucket 4)\"\",\"\"Accounts Roll Forward (Bucket 5)\"\",\"\"Accounts Roll Forward (Bucket 6)\"\",\"\"Accounts Roll Forward (Bucket 7)\"\",\"\"Accounts Roll Forward (Bucket 8)\"\"]",
			"[\"\"3628\"\",\"\"3629\"\",\"\"3630\"\",\"\"3631\"\",\"\"3632\"\",\"\"3633\"\",\"\"3634\"\",\"\"3635\"\",\"\"3636\"\"]:[\"\"Accounts Stabilized (Bucket 0)\"\",\"\"Accounts Stabilized (Bucket 1)\"\",\"\"Accounts Stabilized (Bucket 2)\"\",\"\"Accounts Stabilized (Bucket 3)\"\",\"\"Accounts Stabilized (Bucket 4)\"\",\"\"Accounts Stabilized (Bucket 5)\"\",\"\"Accounts Stabilized (Bucket 6)\"\",\"\"Accounts Stabilized (Bucket 7)\"\",\"\"Accounts Stabilized (Bucket 8)\"\"]",
			"[\"\"3641\"\",\"\"3642\"\",\"\"3643\"\",\"\"3644\"\",\"\"3645\"\",\"\"3646\"\",\"\"3647\"\",\"\"3648\"\"]:[\"\"EOP Outstanding Normalized (Bucket 1)\"\",\"\"EOP Outstanding Normalized (Bucket 2)\"\",\"\"EOP Outstanding Normalized (Bucket 3)\"\",\"\"EOP Outstanding Normalized (Bucket 4)\"\",\"\"EOP Outstanding Normalized (Bucket 5)\"\",\"\"EOP Outstanding Normalized (Bucket 6)\"\",\"\"EOP Outstanding Normalized (Bucket 7)\"\",\"\"EOP Outstanding Normalized (Bucket 8)\"\"]",
			"[\"\"3654\"\",\"\"3655\"\",\"\"3656\"\",\"\"3657\"\",\"\"3658\"\",\"\"3659\"\",\"\"3660\"\",\"\"3661\"\"]:[\"\"EOP Outstanding Roll Back (Bucket 1)\"\",\"\"EOP Outstanding Roll Back (Bucket 2)\"\",\"\"EOP Outstanding Roll Back (Bucket 3)\"\",\"\"EOP Outstanding Roll Back (Bucket 4)\"\",\"\"EOP Outstanding Roll Back (Bucket 5)\"\",\"\"EOP Outstanding Roll Back (Bucket 6)\"\",\"\"EOP Outstanding Roll Back (Bucket 7)\"\",\"\"EOP Outstanding Roll Back (Bucket 8)\"\"]",
			"[\"\"3667\"\",\"\"3668\"\",\"\"3669\"\",\"\"3670\"\",\"\"3671\"\",\"\"3672\"\",\"\"3673\"\",\"\"3674\"\",\"\"3675\"\"]:[\"\"EOP Outstanding Roll Forward (Bucket 0)\"\",\"\"EOP Outstanding Roll Forward (Bucket 1)\"\",\"\"EOP Outstanding Roll Forward (Bucket 2)\"\",\"\"EOP Outstanding Roll Forward (Bucket 3)\"\",\"\"EOP Outstanding Roll Forward (Bucket 4)\"\",\"\"EOP Outstanding Roll Forward (Bucket 5)\"\",\"\"EOP Outstanding Roll Forward (Bucket 6)\"\",\"\"EOP Outstanding Roll Forward (Bucket 7)\"\",\"\"EOP Outstanding Roll Forward (Bucket 8)\"\"]",
			"[\"\"3680\"\",\"\"3681\"\",\"\"3682\"\",\"\"3683\"\",\"\"3684\"\",\"\"3685\"\",\"\"3686\"\",\"\"3687\"\",\"\"3688\"\"]:[\"\"EOP Outstanding Stabilized (Bucket 0)\"\",\"\"EOP Outstanding Stabilized (Bucket 1)\"\",\"\"EOP Outstanding Stabilized (Bucket 2)\"\",\"\"EOP Outstanding Stabilized (Bucket 3)\"\",\"\"EOP Outstanding Stabilized (Bucket 4)\"\",\"\"EOP Outstanding Stabilized (Bucket 5)\"\",\"\"EOP Outstanding Stabilized (Bucket 6)\"\",\"\"EOP Outstanding Stabilized (Bucket 7)\"\",\"\"EOP Outstanding Stabilized (Bucket 8)\"\"]",
			"[\"\"21\"\",\"\"22\"\"]:[\"\"# Total Exception Applications\"\",\"\"Total Exception Applications (%)\"\"]",
			"[\"\"8\"\",\"\"16\"\",\"\"30\"\",\"\"31\"\",\"\"32\"\",\"\"624\"\",\"\"2459\"\"]:[\"\"# Apps Received\"\",\"\"Approval Rate\"\",\"\"Average Bureau Balance\"\",\"\"Average Bureau Enquiries\"\",\"\"Average Bureau Lines\"\",\"\"Hit %\"\",\"\"Pulled through rate\"\"]",
			"[\"\"8\"\",\"\"9\"\"]:[\"\"# Apps Received\"\",\"\"# Approvals Received\"\"]",
			"[\"\"16\"\",\"\"1420\"\",\"\"2465\"\"]:[\"\"Approval Rate\"\",\"\"Cancelled Rate\"\",\"\"Pull through rate (%)\"\"]",
			"[\"\"7\"\"]:[\"\"Average Credit Line\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"8\"\",\"\"16\"\",\"\"24\"\",\"\"2459\"\"]:[\"\"# Apps Received\"\",\"\"Approval Rate\"\",\"\"Deviation exposure % to total approved exposure\"\",\"\"Pulled through rate\"\"]",
			"[\"\"9\"\"]:[\"\"New Volume\"\"]",
			"[\"\"3547\"\",\"\"3549\"\",\"\"3550\"\",\"\"3548\"\"]:[\"\"# Collateral Units\"\",\"\"Market Value of Collateral Units\"\",\"\"Collateral Market Value To Collateral Original Value (%)\"\",\"\"Original Value of Collateral Units\"\"]",
			"[\"\"3582\"\",\"\"3583\"\"]:[\"\"Total Amount Foreclosed\"\",\"\"Total Amount Foreclosed to Total Overdue\"\"]",
			"[\"\"9\"\",\"\"24\"\",\"\"16\"\"]:[\"\"# Approvals Received\"\",\"\"Deviation exposure % to total approved exposure\"\",\"\"Approval Rate\"\"]",
			"[\"\"8\"\",\"\"16\"\",\"\"1056\"\",\"\"2459\"\"]:[\"\"# Apps Received\"\",\"\"Approval Rate\"\",\"\"# Apps Rejected\"\",\"\"Pulled through rate\"\"]",
			"[\"\"2452\"\"]:[\"\"Disburse Amount\"\"]",
			"[\"\"1056\"\"]:[\"\"# Apps Rejected\"\"]",
			"[\"\"1057\"\"]:[\"\"Rejected Apps %\"\"]",
			"[\"\"1057\"\"]:[\"\"Rejected Apps %\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"8\"\",\"\"9\"\",\"\"1056\"\",\"\"2370\"\",\"\"42\"\",\"\"43\"\"]:[\"\"# Apps Received\"\",\"\"# Apps Approved\"\",\"\"# Apps Rejected\"\",\"\"# Apps Cancelled\"\",\"\"# High Score Overrides\"\",\"\"# Low Score Overrides\"\"]",
			"[\"\"8\"\",\"\"9\"\",\"\"42\"\",\"\"43\"\",\"\"2370\"\",\"\"1056\"\"]:[\"\"# Apps Received\"\",\"\"# Apps Approved\"\",\"\"# High Score Overrides\"\",\"\"# Low Score Overrides\"\",\"\"# Apps Cancelled\"\",\"\"# Apps Rejected\"\"]",
			"[\"\"2473\"\"]:[\"\"Deviations %\"\"]",
			"[\"\"2473\"\"]:[\"\"Deviations %\"\"]",
			"[\"\"1057\"\"]:[\"\"Rejected Apps %\"\"]",
			"[\"\"8\"\",\"\"16\"\",\"\"24\"\",\"\"2459\"\"]:[\"\"# Apps Received\"\",\"\"Approval Rate\"\",\"\"Deviation Rate\"\",\"\"Pulled through rate\"\"]",
			"[\"\"16\"\"]:[\"\"Approval Rate\"\"]",
			"[\"\"8\"\",\"\"16\"\",\"\"2371\"\",\"\"2454\"\"]:[\"\"# Apps Received\"\",\"\"Approval Rate\"\",\"\"Cancelled Rate\"\",\"\"Write Rate (%) - #\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"16\"\",\"\"635\"\",\"\"2465\"\",\"\"8\"\"]:[\"\"Approval Rate\"\",\"\"# New Accounts Approved\"\",\"\"Pull through rate (%)\"\",\"\"# Apps Received\"\"]",
			"[\"\"8\"\",\"\"9\"\",\"\"635\"\",\"\"16\"\",\"\"2465\"\",\"\"1057\"\",\"\"1420\"\"]:[\"\"# Apps Received\"\",\"\"# Apps Approved\"\",\"\"# New Accounts Approved\"\",\"\"Approval Rate\"\",\"\"Pull through rate (%)\"\",\"\"Rejected Apps %\"\",\"\"Cancelled Rate\"\"]",
			"[\"\"8\"\",\"\"16\"\",\"\"635\"\",\"\"2465\"\"]:[\"\"# Apps Received\"\",\"\"Approval Rate\"\",\"\"# New Accounts Approved\"\",\"\"Pull through rate (%)\"\"]",
			"[\"\"8\"\",\"\"16\"\",\"\"635\"\",\"\"2465\"\"]:[\"\"# Apps Received\"\",\"\"Approval Rate\"\",\"\"# New Accounts Approved\"\",\"\"Pull through rate (%)\"\"]",
			"[\"\"8\"\",\"\"16\"\",\"\"635\"\",\"\"2465\"\"]:[\"\"# Apps Received\"\",\"\"Approval Rate\"\",\"\"# New Accounts Approved\"\",\"\"Pull through rate (%)\"\"]",
			"[\"\"8\"\",\"\"16\"\",\"\"635\"\",\"\"2465\"\"]:[\"\"# Apps Received\"\",\"\"Approval Rate\"\",\"\"# New Accounts Approved\"\",\"\"Pull through rate (%)\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"30\"\",\"\"32\"\",\"\"2728\"\",\"\"2729\"\"]:[\"\"Average Bureau Balance\"\",\"\"Average Bureau Lines\"\",\"\"Average Bureau Balance By Line\"\",\"\"Bureau Balance By Line\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"9\"\",\"\"2370\"\"]:[\"\"# Apps Approved\"\",\"\"# Apps Cancelled\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"7\"\",\"\"635\"\"]:[\"\"Average Credit Line\"\",\"\"# New Accounts Approved\"\"]",
			"[\"\"635\"\",\"\"4\"\"]:[\"\"# New Accounts Approved\"\",\"\"Amount Approved\"\"]",
			"[\"\"16\"\",\"\"1420\"\",\"\"17\"\"]:[\"\"Approval Rate\"\",\"\"Cancelled Rate\"\",\"\"Decline Rate\"\"]",
			"[\"\"1057\"\"]:[\"\"Rejected Apps %\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"635\"\"]:[\"\"# New Accounts Approved\"\"]",
			"[\"\"8\"\",\"\"9\"\",\"\"16\"\"]:[\"\"# Apps Received\"\",\"\"# Apps Approved\"\",\"\"Approval Rate\"\"]",
			"[\"\"1420\"\"]:[\"\"Cancelled Rate\"\"]",
			"[\"\"1420\"\"]:[\"\"Cancelled Rate\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"9\"\",\"\"1056\"\",\"\"2733\"\"]:[\"\"# Apps Approved\"\",\"\"# Apps Rejected\"\",\"\"Sum of Apps approved and reject\"\"]",
			"[\"\"8\"\",\"\"9\"\",\"\"1056\"\"]:[\"\"# Apps Received\"\",\"\"# Apps Approved\"\",\"\"# Apps Rejected\"\"]",
			"[\"\"381\"\",\"\"380\"\"]:[\"\"ANR\"\",\"\"Average EOP Outstanding\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"4\"\"]:[\"\"Amount Approved\"\"]",
			"[\"\"9\"\",\"\"2370\"\"]:[\"\"# Apps Approved\"\",\"\"# Apps Cancelled\"\"]",
			"[\"\"4\"\",\"\"16\"\",\"\"17\"\"]:[\"\"Amount Approved\"\",\"\"Approval Rate\"\",\"\"Decline Rate\"\"]",
			"[\"\"9\"\",\"\"2370\"\"]:[\"\"# Apps Approved\"\",\"\"# Apps Cancelled\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"2471\"\",\"\"2472\"\"]:[\"\"# Total Deviations (On Group Application)\"\",\"\"Number of Deviations to total approval (On Group Application) %\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"134\"\",\"\"136\"\",\"\"135\"\"]:[\"\"Accounts Improve (2)\"\",\"\"Accounts Hold (1)\"\",\"\"Accounts Worsen (1)\"\"]",
			"[\"\"142\"\",\"\"144\"\",\"\"143\"\"]:[\"\"Accounts Improve (3)\"\",\"\"Accounts Hold (2)\"\",\"\"Accounts Worsen (2)\"\"]",
			"[\"\"150\"\",\"\"152\"\",\"\"151\"\"]:[\"\"Accounts Improve (4)\"\",\"\"Accounts Hold (3)\"\",\"\"Accounts Worsen (3)\"\"]",
			"[\"\"158\"\",\"\"160\"\",\"\"159\"\"]:[\"\"Acc Improve (5)\"\",\"\"Acc Hold (4)\"\",\"\"Acc Worsen (4)\"\"]",
			"[\"\"166\"\",\"\"168\"\",\"\"167\"\"]:[\"\"Accounts Improve (6)\"\",\"\"Accounts Hold (5)\"\",\"\"Accounts Worsen (5)\"\"]",
			"[\"\"174\"\",\"\"176\"\",\"\"175\"\"]:[\"\"Accounts Improve (7)\"\",\"\"Accounts Hold (6)\"\",\"\"Accounts Worsen (6)\"\"]",
			"[\"\"182\"\",\"\"184\"\",\"\"183\"\"]:[\"\"Accounts Improve (8)\"\",\"\"Accounts Hold (7)\"\",\"\"Accounts Worsen (7)\"\"]",
			"[\"\"190\"\",\"\"192\"\",\"\"191\"\"]:[\"\"Accounts Improve (9)\"\",\"\"Accounts Hold (8)\"\",\"\"Accounts Worsen (8)\"\"]",
			"[\"\"198\"\",\"\"200\"\",\"\"199\"\"]:[\"\"Accounts Improve (10)\"\",\"\"Accounts Hold (9)\"\",\"\"Accounts Worsen (9)\"\"]",
			"[\"\"206\"\",\"\"208\"\",\"\"207\"\"]:[\"\"Accounts Improve (11)\"\",\"\"Accounts Hold (10)\"\",\"\"Accounts Worsen (10)\"\"]",
			"[\"\"214\"\",\"\"216\"\",\"\"215\"\"]:[\"\"Accounts Improve (12)\"\",\"\"Accounts Hold (11)\"\",\"\"Accounts Worsen (11)\"\"]",
			"[\"\"222\"\",\"\"224\"\",\"\"223\"\"]:[\"\"Accounts Improve (13)\"\",\"\"Accounts Hold (12)\"\",\"\"Accounts Worsen (12)\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"8\"\",\"\"16\"\",\"\"2459\"\"]:[\"\"# Apps Received\"\",\"\"Approval Rate\"\",\"\"Pulled through rate\"\"]",
			"[\"\"138\"\",\"\"140\"\",\"\"139\"\"]:[\"\"OS Improve (2) (%)\"\",\"\"OS Hold (1) (%)\"\",\"\"OS Worsen (1) (%)\"\"]",
			"[\"\"146\"\",\"\"148\"\",\"\"147\"\"]:[\"\"OS Improve (3) (%)\"\",\"\"OS Hold (2) (%)\"\",\"\"OS Worsen (2) (%)\"\"]",
			"[\"\"154\"\",\"\"156\"\",\"\"155\"\"]:[\"\"OS Improve (4) (%)\"\",\"\"OS Hold (3) (%)\"\",\"\"OS Worsen (3) (%)\"\"]",
			"[\"\"162\"\",\"\"164\"\",\"\"163\"\"]:[\"\"OS Improve (5) (%)\"\",\"\"OS Hold (4) (%)\"\",\"\"OS Worsen (4) (%)\"\"]",
			"[\"\"170\"\",\"\"172\"\",\"\"171\"\"]:[\"\"OS Improve (6) (%)\"\",\"\"OS Hold (5) (%)\"\",\"\"OS Worsen (5) (%)\"\"]",
			"[\"\"178\"\",\"\"180\"\",\"\"179\"\"]:[\"\"OS Improve (7) (%)\"\",\"\"OS Hold (6) (%)\"\",\"\"OS Worsen (6) (%)\"\"]",
			"[\"\"186\"\",\"\"188\"\",\"\"187\"\"]:[\"\"OS Improve (8) (%)\"\",\"\"OS Hold (7) (%)\"\",\"\"OS Worsen (7) (%)\"\"]",
			"[\"\"194\"\",\"\"196\"\",\"\"195\"\"]:[\"\"OS Improve (9) (%)\"\",\"\"OS Hold (8) (%)\"\",\"\"OS Worsen (8) (%)\"\"]",
			"[\"\"202\"\",\"\"204\"\",\"\"203\"\"]:[\"\"OS Improve (10) (%)\"\",\"\"OS Hold (9) (%)\"\",\"\"OS Worsen (9) (%)\"\"]",
			"[\"\"210\"\",\"\"212\"\",\"\"211\"\"]:[\"\"OS Improve (11) (%)\"\",\"\"OS Hold (10) (%)\"\",\"\"OS Worsen (10) (%)\"\"]",
			"[\"\"218\"\",\"\"220\"\",\"\"219\"\"]:[\"\"OS Improve (12) (%)\"\",\"\"OS Hold (11) (%)\"\",\"\"OS Worsen (11) (%)\"\"]",
			"[\"\"226\"\",\"\"227\"\",\"\"228\"\"]:[\"\"OS Improve (13) (%)\"\",\"\"OS Worsen (12) (%)\"\",\"\"OS Hold (12) (%)\"\"]",
			"[\"\"9\"\",\"\"2370\"\"]:[\"\"# Apps Approved\"\",\"\"# Apps Cancelled\"\"]",
			"[\"\"9\"\",\"\"16\"\",\"\"635\"\",\"\"2364\"\",\"\"2366\"\",\"\"1056\"\"]:[\"\"# Apps Approved\"\",\"\"Approval Rate\"\",\"\"# New Accounts Approved\"\",\"\"# Apps Cancelled\"\",\"\"# Apps Pending\"\",\"\"# Apps Rejected\"\"]",
			"[\"\"16\"\",\"\"4\"\"]:[\"\"Approval Rate\"\",\"\"Amount Approved\"\"]",
			"[\"\"9\"\",\"\"16\"\"]:[\"\"# Apps Approved\"\",\"\"Approval Rate\"\"]",
			"[\"\"381\"\",\"\"952\"\"]:[\"\"ANR\"\",\"\"Total Outstanding\"\"]",
			"[\"\"952\"\",\"\"381\"\"]:[\"\"Total Outstanding\"\",\"\"ANR\"\"]",
			"[\"\"1045\"\",\"\"2492\"\",\"\"952\"\"]:[\"\"Total Bankrupt Outstanding\"\",\"\"Gross Credit Loss\"\",\"\"Total Outstanding\"\"]",
			"[\"\"8\"\",\"\"9\"\"]:[\"\"# Apps Received\"\",\"\"# Approvals Received\"\"]",
			"[\"\"3753\"\"]:[\"\"30+ Coincident Outstanding (%)\"\"]",
			"[\"\"381\"\"]:[\"\"ANR\"\"]",
			"[\"\"9\"\",\"\"8\"\"]:[\"\"# Apps Approved\"\",\"\"# Apps Received\"\"]",
			"[\"\"1022\"\"]:[\"\"Average Loan Size / New Account\"\"]",
			"[\"\"2612\"\"]:[\"\"Average Current LTV\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"379\"\"]:[\"\"EOP Outstanding\"\"]",
			"[\"\"9\"\",\"\"16\"\"]:[\"\"# Apps Approved\"\",\"\"Approval Rate\"\"]",
			"[\"\"9\"\",\"\"16\"\"]:[\"\"# Apps Approved\"\",\"\"Approval Rate\"\"]",
			"[\"\"9\"\",\"\"1056\"\"]:[\"\"# Apps Approved\"\",\"\"# Apps Rejected\"\"]",
			"[\"\"9\"\",\"\"2370\"\"]:[\"\"# Apps Approved\"\",\"\"# Apps Cancelled\"\"]",
			"[\"\"9\"\",\"\"2370\"\"]:[\"\"# Apps Approved\"\",\"\"# Apps Cancelled\"\"]",
			"[\"\"9\"\",\"\"2370\"\"]:[\"\"# Apps Approved\"\",\"\"# Apps Cancelled\"\"]",
			"[\"\"952\"\"]:[\"\"Total Outstanding\"\"]",
			"[\"\"2617\"\"]:[\"\"Ever X+ DPD #\"\"]",
			"[\"\"135\"\",\"\"143\"\",\"\"151\"\",\"\"159\"\",\"\"167\"\",\"\"175\"\"]:[\"\"Accounts Roll Forward (Bucket 1)\"\",\"\"Accounts Roll Forward (Bucket 2)\"\",\"\"Accounts Roll Forward (Bucket 3)\"\",\"\"Accounts Roll Forward (Bucket 4)\"\",\"\"Accounts Roll Forward (Bucket 5)\"\",\"\"Accounts Roll Forward (Bucket 6)\"\"]",
			"[\"\"3737\"\",\"\"3738\"\",\"\"3739\"\",\"\"3740\"\",\"\"3741\"\",\"\"3742\"\",\"\"3743\"\",\"\"3744\"\",\"\"3745\"\",\"\"3746\"\",\"\"3747\"\",\"\"3748\"\",\"\"3750\"\",\"\"3751\"\",\"\"3752\"\",\"\"3749\"\"]:[\"\"CURRENT ($ OS)\"\",\"\"X - DAY ($ OS)\"\",\"\"30 - 59 ($ OS)\"\",\"\"60 - 89 ($ OS)\"\",\"\"90 - 119 ($ OS)\"\",\"\"120 - 149 ($ OS)\"\",\"\"150 - 179 ($ OS)\"\",\"\"180 - 209 ($ OS)\"\",\"\"210 - 239 ($ OS)\"\",\"\"240 - 269 ($ OS)\"\",\"\"270 - 299 ($ OS)\"\",\"\"300 - 329 ($ OS)\"\",\"\"360 - 389 ($ OS)\"\",\"\"390 + ($ OS)\"\",\"\"EARLY WRTE-OFF ($ OS)\"\",\"\"330 - 359 ($ OS)\"\"]",
			"[\"\"3721\"\",\"\"3722\"\",\"\"3723\"\",\"\"3724\"\",\"\"3725\"\",\"\"3726\"\",\"\"3727\"\",\"\"3728\"\",\"\"3729\"\",\"\"3730\"\",\"\"3731\"\",\"\"3732\"\",\"\"3733\"\",\"\"3734\"\",\"\"3735\"\",\"\"3736\"\"]:[\"\"CURRENT (# Accounts)\"\",\"\"X - DAY (# Accounts)\"\",\"\"30 - 59 (# Accounts)\"\",\"\"60 - 89 (# Accounts)\"\",\"\"90 - 119 (# Accounts)\"\",\"\"120 - 149 (# Accounts)\"\",\"\"150 - 179 (# Accounts)\"\",\"\"180 - 209 (# Accounts)\"\",\"\"210 - 239 (# Accounts)\"\",\"\"240 - 269 (# Accounts)\"\",\"\"270 - 299 (# Accounts)\"\",\"\"300 - 329 (# Accounts)\"\",\"\"330 - 359 (# Accounts)\"\",\"\"360 - 389 (# Accounts)\"\",\"\"390 + (# Accounts)\"\",\"\"EARLY WRTE-OFF (# Accounts)\"\"]",
			"[\"\"50\"\",\"\"952\"\"]:[\"\"# Accounts\"\",\"\"Total Outstanding\"\"]",
			"[\"\"2474\"\",\"\"2475\"\",\"\"2476\"\"]:[\"\"%FPD X (FPD)\"\",\"\"%FPD 30 (SPD)\"\",\"\"%FPD 60 (TPD)\"\"]",
			"[\"\"2607\"\",\"\"2608\"\"]:[\"\"NPL Balance\"\",\"\"%NPL\"\"]",
			"[\"\"2491\"\",\"\"2609\"\",\"\"2610\"\"]:[\"\"% Credit Cost\"\",\"\"Reserve Balance\"\",\"\"%Coverage\"\"]",
			"[\"\"344\"\",\"\"79\"\"]:[\"\"Total Revenue\"\",\"\"Revenue % ANR\"\"]",
			"[\"\"982\"\"]:[\"\"Ever 30+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"984\"\"]:[\"\"Ever 90+ DPD Outstanding to Total Amount Booked\"\"]",
			"[\"\"66\"\"]:[\"\"30 + (%) Coincident EOP Outstanding\"\"]",
			"[\"\"963\"\",\"\"444\"\"]:[\"\"# Fraud Write-Off Accounts\"\",\"\"Total Fraud Write-Off Amount\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"9\"\",\"\"2370\"\"]:[\"\"# Apps Approved\"\",\"\"# Apps Cancelled\"\"]",
			"[\"\"379\"\",\"\"50\"\"]:[\"\"EOP Outstanding\"\",\"\"# Accounts\"\"]",
			"[\"\"60\"\"]:[\"\"30 + (%) Lagged Acc\"\"]",
			"[\"\"50\"\",\"\"378\"\",\"\"485\"\",\"\"74\"\"]:[\"\"# Accounts\"\",\"\"Total # Active Accounts\"\",\"\"# Accounts - VA\"\",\"\"% Active Accounts\"\"]",
			"[\"\"9\"\"]:[\"\"# Apps Approved\"\"]",
			"[\"\"50\"\"]:[\"\"# Accounts\"\"]",
			"[\"\"9\"\",\"\"2370\"\"]:[\"\"# Apps Approved\"\",\"\"# Apps Cancelled\"\"]",
			"[\"\"50\"\",\"\"62\"\",\"\"378\"\"]:[\"\"# Accounts\"\",\"\"30 + (%) Coincident Accounts\"\",\"\"Total # Active Accounts\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"50\"\"]:[\"\"# Accounts\"\"]",
			"[\"\"952\"\"]:[\"\"Total Outstanding\"\"]",
			"[\"\"7\"\"]:[\"\"Average Ticket Size\"\"]",
			"[\"\"16\"\",\"\"2459\"\",\"\"24\"\"]:[\"\"Approval Rate\"\",\"\"Pulled through rate\"\",\"\"Deviation Rate\"\"]",
			"[\"\"4\"\"]:[\"\"Amount Approved\"\"]",
			"[\"\"952\"\"]:[\"\"Total Outstanding\"\"]",
			"[\"\"66\"\",\"\"68\"\",\"\"2608\"\"]:[\"\"30 + (%) Coincident EOP Outstanding\"\",\"\"90 + (%) Coincident EOP Outstanding\"\",\"\"%NPL\"\"]",
			"[\"\"2607\"\"]:[\"\"NPL Balance\"\"]",
			"[\"\"8\"\",\"\"16\"\",\"\"2459\"\"]:[\"\"# Apps Received\"\",\"\"Approval Rate\"\",\"\"Pulled through rate\"\"]",
			"[\"\"1056\"\"]:[\"\"# Apps Rejected\"\"]",
			"[\"\"1056\"\"]:[\"\"# Apps Rejected\"\"]",
			"[\"\"4\"\"]:[\"\"Amount Approved\"\"]",
			"[\"\"4\"\"]:[\"\"Amount Approved\"\"]",
			"[\"\"952\"\"]:[\"\"Total Outstanding\"\"]",
			"[\"\"66\"\",\"\"2608\"\",\"\"68\"\"]:[\"\"30 + (%) Coincident EOP Outstanding\"\",\"\"%NPL\"\",\"\"90 + (%) Coincident EOP Outstanding\"\"]",
			"[\"\"417\"\"]:[\"\"30+ Delinquent EOP Outstanding\"\"]",
			"[\"\"417\"\"]:[\"\"30+ Delinquent EOP Outstanding\"\"]",
			"[\"\"417\"\"]:[\"\"30+ Delinquent EOP Outstanding\"\"]",
			"[\"\"1056\"\"]:[\"\"# Apps Rejected\"\"]",
			"[\"\"9\"\"]:[\"\"New Volume\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"952\"\"]:[\"\"Total Outstanding\"\"]",
			"[\"\"952\"\"]:[\"\"Total Outstanding\"\"]",
			"[\"\"8\"\"]:[\"\"# Apps Received\"\"]",
			"[\"\"4266\"\"]:[\"\"Eop/Account\"\"]",
			"[\"\"2607\"\"]:[\"\"NPL Balance\"\"]",
			"[\"\"9\"\",\"\"2364\"\"]:[\"\"# Apps Approved\"\",\"\"# Apps Cancelled\"\"]",
			"[\"\"3753\"\"]:[\"\"30 + Coincident Outstanding (%)\"\"]",
			"[\"\"4\"\",\"\"635\"\"]:[\"\"Lines Booked\"\",\"\"#New Accounts\"\"]",
			"[\"\"11\"\",\"\"9\"\"]:[\"\"# Decisioned Applications\"\",\"\"# Apps Approved\"\"]",
			"[\"\"9\"\",\"\"11\"\"]:[\"\"# Apps Approved\"\",\"\"# Decisioned Applications\"\"]",
			"[\"\"952\"\"]:[\"\"Total Outstanding\"\"]",
			"[\"\"50\"\",\"\"952\"\",\"\"953\"\"]:[\"\"# Accounts\"\",\"\"Total Outstanding\"\",\"\"Total Overdue\"\"]",
			"[\"\"50\"\",\"\"342\"\",\"\"380\"\",\"\"1023\"\",\"\"1406\"\",\"\"1408\"\",\"\"931\"\"]:[\"\"# Accounts\"\",\"\"Average APR\"\",\"\"Average EOP Outstanding\"\",\"\"Average Loan Size /Account bkp\"\",\"\"Loan Size\"\",\"\"ENR %\"\",\"\"Market Value of Collateral Units\"\"]",
			"[\"\"635\"\",\"\"9\"\"]:[\"\"# New Accounts Approved\"\",\"\"# Apps Approved\"\"]",
			"[\"\"2478\"\",\"\"2480\"\"]:[\"\"%VT30+ @ 6 MOB\"\",\"\"%VT30+ @ 12 MOB\"\"]",
			"[\"\"635\"\",\"\"4\"\"]:[\"\"# New Accounts Approved\"\",\"\"Amount Approved\"\"]",
			"[\"\"3753\"\"]:[\"\"30 + Coincident Outstanding (%)\"\""};

}
